# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.10/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: basemaps-config-create
  labels:
    linz.govt.nz/category: basemaps
spec:
  entrypoint: main
  podMetadata:
    labels:
      linz.govt.nz/category: basemaps
  arguments:
    parameters:
      - name: version_basemaps_cli
        value: 'v8'
      - name: location
        value: 's3://bucket/path/to'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: create-config
            template: create-config
            arguments:
              parameters:
                - name: location
                  value: '{{workflow.parameters.location}}'
    - name: create-config
      inputs:
        parameters:
          - name: location
            description: Location of the imagery to create config for
      container:
        image: ghcr.io/linz/basemaps/cli:{{=sprig.trim(workflow.parameters.version_basemaps_cli)}}
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - 'config'
          - 'create-config'
          - '{{ inputs.parameters.location }}'
      outputs:
        parameters:
          - name: url
            description: Basemaps URL to view the imagery
            valueFrom:
              path: '/tmp/cogify/config-url'
          - name: config
            description: Location of the config file
            valueFrom:
              path: '/tmp/cogify/config-path'
