# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.10/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: basemaps-create-overview-
  namespace: argo
  labels:
    linz.govt.nz/category: basemaps
    linz.govt.nz/data-type: raster
spec:
  entrypoint: main
  podMetadata:
    labels:
      linz.govt.nz/category: basemaps
      linz.govt.nz/data-type: raster
  arguments:
    parameters:
      - name: version_basemaps_cli
        value: 'v6'
      - name: source
        value: ''
      - name: output
        value: ''
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: create-overview
            template: create-overview
            arguments:
              parameters:
                - name: source
                  value: '{{workflow.parameters.source}}'
                - name: output
                  value: '{{workflow.parameters.output}}'
    - name: create-overview
      inputs:
        parameters:
          - name: source
          - name: output
      container:
        image: ghcr.io/linz/basemaps/cli:{{workflow.parameters.version_basemaps_cli}}
        resources:
          requests:
            cpu: 3000m
            memory: 7.8Gi
        command: [node, index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          [
            '-V',
            'create-overview',
            '--source',
            '{{inputs.parameters.source}}',
            '--output',
            '{{inputs.parameters.output}}',
          ]
