---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stac-validate
  namespace: argo
  labels:
    linz.govt.nz/category: stac
spec:
  parallelism: 20
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  arguments:
    parameters:
      - name: version_argo_tasks
        value: 'v3'
      - name: uri
        description: 'Path(s) to the STAC file(s).'
        value: 's3://linz-imagery-staging/test/stac-validate/'
      - name: include
        value: 'collection.json$'
      - name: checksum
        description: 'Validate asset checksums.'
        value: 'false'
        enum:
          - 'false'
          - 'true'
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list-collections
            template: aws-list-collections
          - name: stac-validate-collections
            template: stac-validate-collections
            arguments:
              parameters:
                - name: file
                  value: '{{item}}'
            depends: aws-list-collections
            withParam: '{{tasks.aws-list-collections.outputs.parameters.files}}'
    - name: aws-list-collections
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            'list',
            '--verbose',
            '--include',
            '{{=sprig.trim(workflow.parameters.include)}}',
            '--group',
            '1',
            '--output',
            '/tmp/file_list.json',
            '{{=sprig.trim(workflow.parameters.uri)}}',
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: stac-validate-collections
      inputs:
        parameters:
          - name: file
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        resources:
          requests:
            cpu: 15000m
            memory: 7.8Gi
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            'stac',
            'validate',
            '--concurrency',
            '50',
            '--recursive',
            '--checksum={{workflow.parameters.checksum}}',
            '{{inputs.parameters.file}}',
          ]
