---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: stac-validate-v1.0.0-18
  namespace: argo
spec:
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: stac-file-path
        value: "s3://linz-imagery-staging/test/stac-validate/collection.json"
  templates:
    - name: main
      dag:
        tasks:
          - name: stac-validate
            template: stac-validate
            arguments:
              parameters:
                - name: stac-file-path
                  value: "{{workflow.parameters.stac-file-path}}"
    - name: stac-validate
      inputs:
        parameters:
          - name: stac-file-path
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-18-gea46732
        command: [node, /app/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-v2.json
        args:
          [
            "stac-validate",
            "--recursive",
            "{{inputs.parameters.stac-file-path}}",
          ]
      outputs:
        parameters:
          - name: stac-results
            value: {{tasks.stac-validate.outputs.result}}
