apiVersion: v1
kind: ServiceAccount
metadata:
name: workflow-runner-sa
namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: argo-workflows-workflow
namespace: ${NAMESPACE}
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'watch', 'list', 'create', 'delete', 'patch']
  - apiGroups: ['']
    resources: ['pods/log']
    verbs: ['get', 'watch']
  - apiGroups: ['']
    resources: ['pods/exec']
    verbs: ['create']
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'watch', 'list']
  - apiGroups: ['argoproj.io']
    resources: ['workflows']
    verbs: ['get', 'watch', 'list', 'create', 'delete', 'update']
  - apiGroups: ['argoproj.io']
    resources: ['workflowtaskresults']
    verbs: ['create', 'patch']
  - apiGroups: ['argoproj.io']
    resources: ['workflowtasksets', 'workflowartifactgctasks']
    verbs: ['list', 'watch']
  - apiGroups: ['argoproj.io']
    resources: ['workflowtasksets/status', 'workflowartifactgctasks/status']
    verbs: ['patch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
name: argo-workflows-workflow
namespace: ${NAMESPACE}
roleRef:
  kind: Role
  name: argo-workflows-workflow
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: workflow-runner-sa
    namespace: ${NAMESPACE}
