# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template uses container https://github.com/linz/geoprocessor/pkgs/container/geoprocessor%2Fraster
  # see https://github.com/linz/geoprocessor/blob/master/packages/geoprocessor-raster/src/geoprocessor_raster/collection_from_items.py
  name: tpl-gp-raster-create-collection
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: version_geoprocessor_raster
            description: 'Specify a version of the geoprocessor/raster image to use, e.g. "v4.8" or "latest"'
            default: 'v10'

          - name: collection_id
            description: 'Collection ID of existing dataset, or else a generated collection ID'
            default: ''

          - name: linz_slug
            description: 'Dataset identifying slug'
            default: ''

          - name: odr_url
            description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-imagery/taranaki/new-plymouth_2017_0.1m/rgb/2193/"'
            default: ''

          - name: delete_all_existing_items
            description: 'Delete all existing items in the collection before adding new items'
            default: 'false'
            enum:
              - 'true'
              - 'false'

          - name: location
            description: 'Location for output files'
            default: ''

          - name: current_datetime
            description: 'Current date and time of the workflow'
            default: ''

          - name: category
            description: 'Geospatial category of the dataset'
            default: ''

          - name: domain
            description: 'domain of the dataset, e.g. "land", "coastal"'
            default: 'land'
            enum:
              - 'land'
              - 'coastal'

          - name: region
            description: 'Region of the dataset'
            default: ''

          - name: gsd
            description: 'Dataset GSD in metres, e.g., "0.3" for 30 centimetres'
            default: ''

          - name: data_type
            description: 'Data type of the dataset pixels, e.g. "uint16"'
            default: ''

          - name: geographic_description
            description: '(Optional) Additional dataset description, to be used in the title in place of the Region, e.g. "Hamilton"'
            default: ''

          - name: event
            description: '(Optional) Event name if dataset has been captured in association with an event, e.g. "Top of the South Floods"'
            default: ''

          - name: historic_survey_number
            description: '(Optional) Survey Number associated with historical datasets, e.g. "SN8844"'
            default: ''

          - name: lifecycle
            description: 'The release lifecycle status of the dataset, e.g. "completed or "ongoing"'
            default: ''

          - name: add_title_suffix
            description: 'Add a title suffix to the collection title based on the lifecycle. For example, "[TITLE] - Preview"'
            default: 'false'

          - name: producer
            description: 'The producer of the source dataset, e.g. aerial or bathymetric survey company'
            default: ''

          - name: producer_list
            description: '(Optional) List of imagery producers, separated by semicolon (;). Has no effect unless a semicolon delimited list is entered.'
            default: ''

          - name: licensor
            description: 'The licensor of the dataset, e.g. local or regional council, government agency, satellite provider'
            default: ''

          - name: licensor_list
            description: '(Optional) List of imagery licensors, separated by semicolon (;). Has no effect unless a semicolon delimited list is entered.'
            default: ''

          - name: create_capture_dates
            description: 'Add a capture-dates.geojson.gz file to the collection assets'
            default: 'false'

          - name: keep_description
            description: 'Keep the description of the existing Collection'
            default: 'false'

          - name: keep_title
            description: 'Keep the title of the existing Collection'
            default: 'false'

          - name: supplied_capture_area
            description: '(Optional) location of a supplied GeoJSON capture area file. Must be EPSG:4326. This will be used instead of generating a capture area from the TIFFs. If odr-url is provided, the existing and supplied capture areas will be merged.'
            default: ''

          - name: simplified_capture_area
            description: 'Whether the capture area is generated from simplified footprints of the input TIFFs.'
            default: 'false'

      outputs:
        artifacts:
          - name: capture-area
            path: '/tmp/capture-area.geojson'
            optional: true
            archive:
              none: {}

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/geoprocessor/raster:{{=sprig.trim(inputs.parameters.version_geoprocessor_raster)}}'
        command: [/usr/bin/tini, --, sh, -c]
        env:
          - name: LOCATION
            value: '{{=sprig.trimSuffix("/", inputs.parameters.location)}}'
          - name: COLLECTION_ID
            value: '{{inputs.parameters.collection_id}}'
          - name: LINZ_SLUG
            value: '{{inputs.parameters.linz_slug}}'
          - name: ODR_URL
            value: '{{=sprig.trim(inputs.parameters.odr_url)}}'
          - name: SUPPLIED_CAPTURE_AREA
            value: '{{=sprig.trim(inputs.parameters.supplied_capture_area)}}'
          - name: SIMPLIFIED_CAPTURE_AREA
            value: '{{inputs.parameters.simplified_capture_area}}'
          - name: DELETE_ALL_EXISTING_ITEMS
            value: '{{=sprig.trim(inputs.parameters.delete_all_existing_items)}}'
          - name: CATEGORY
            value: '{{=sprig.trim(inputs.parameters.category)}}'
          - name: DOMAIN
            value: '{{=sprig.trim(inputs.parameters.domain)}}'
          - name: REGION
            value: '{{=sprig.trim(inputs.parameters.region)}}'
          - name: GSD
            value: '{{=sprig.trim(inputs.parameters.gsd)}}'
          - name: DATA_TYPE
            value: '{{=sprig.trim(inputs.parameters.data_type)}}'
          - name: GEOGRAPHIC_DESCRIPTION
            value: '{{=sprig.trim(inputs.parameters.geographic_description)}}'
          - name: EVENT
            value: '{{=sprig.trim(inputs.parameters.event)}}'
          - name: HISTORIC_SURVEY_NUMBER
            value: '{{=sprig.trim(inputs.parameters.historic_survey_number)}}'
          - name: LIFECYCLE
            value: '{{=sprig.trim(inputs.parameters.lifecycle)}}'
          - name: ADD_TITLE_SUFFIX
            value: '{{inputs.parameters.add_title_suffix}}'
          - name: KEEP_DESCRIPTION
            value: '{{inputs.parameters.keep_description}}'
          - name: KEEP_TITLE
            value: '{{inputs.parameters.keep_title}}'
          - name: CREATE_CAPTURE_DATES
            value: '{{inputs.parameters.create_capture_dates}}'
          - name: PRODUCER
            value: '{{inputs.parameters.producer}}'
          - name: PRODUCER_LIST
            value: '{{=sprig.trim(inputs.parameters.producer_list)}}'
          - name: LICENSOR
            value: '{{inputs.parameters.licensor}}'
          - name: LICENSOR_LIST
            value: '{{=sprig.trim(inputs.parameters.licensor_list)}}'
          - name: CURRENT_DATETIME
            value: '{{inputs.parameters.current_datetime}}'
        args:
          - |
            set -- \
              '--uri' \
              "$LOCATION" \
              '--collection-id' \
              "$COLLECTION_ID" \
              '--linz-slug' \
              "$LINZ_SLUG" \
              '--odr-url' \
              "$ODR_URL"

            if [ -n "$SUPPLIED_CAPTURE_AREA" ]; then
              set -- "$@" \
                '--supplied-capture-area' \
                "$SUPPLIED_CAPTURE_AREA"
            fi

            if [ "$SIMPLIFIED_CAPTURE_AREA" != 'false' ]; then
              set -- "$@" \
                '--simplified-capture-area' \
                "$SIMPLIFIED_CAPTURE_AREA"
            fi

            set -- "$@" \
              '--delete-all-existing-items' \
              "$DELETE_ALL_EXISTING_ITEMS" \
              '--category' \
              "$CATEGORY" \
              '--domain' \
              "$DOMAIN" \
              '--region' \
              "$REGION" \
              '--gsd' \
              "$GSD" \
              '--data-type' \
              "$DATA_TYPE" \
              '--geographic-description' \
              "$GEOGRAPHIC_DESCRIPTION" \
              '--event' \
              "$EVENT" \
              '--historic-survey-number' \
              "$HISTORIC_SURVEY_NUMBER" \
              '--lifecycle' \
              "$LIFECYCLE" \
              '--add-title-suffix' \
              "$ADD_TITLE_SUFFIX" \
              '--keep-description' \
              "$KEEP_DESCRIPTION" \
              '--keep-title' \
              "$KEEP_TITLE"

            if [ "$CREATE_CAPTURE_DATES" != 'false' ]; then
              set -- "$@" \
                '--capture-dates' \
                "$CREATE_CAPTURE_DATES"
            fi

            set -- "$@" \
              '--producer' \
              "$PRODUCER" \
              '--producer-list' \
              "$PRODUCER_LIST" \
              '--licensor' \
              "$LICENSOR" \
              '--licensor-list' \
              "$LICENSOR_LIST" \
              '--concurrency' \
              '25' \
              '--current-datetime' \
              "$CURRENT_DATETIME"

            exec collection-from-items "$@"
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
