# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-events/v1.9.10/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: 'wf-object-created'
spec:
  dependencies:
    - name: 'object-created'
      eventSourceName: 'aws-sqs-object-created'
      eventName: 'object-created'
  triggers:
    - template:
        name: 'trigger-wf-object-created'
        argoWorkflow:
          operation: 'submit'
          source:
            resource:
              apiVersion: 'argoproj.io/v1alpha1'
              kind: 'Workflow'
              metadata:
                generateName: 'test-print-'
                namespace: 'argo'
              spec:
                arguments:
                  parameters:
                    - name: 'message'
                      value: ''
                workflowTemplateRef:
                  name: 'test-print'
                  parameters:
                    - src:
                        dependencyName: 'object-created'
                        dataKey: 'body'
                      dest: 'spec.arguments.parameters.0.value'
