# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-events/v1.9.10/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: 'wf-bucket-events'
spec:
  template:
    serviceAccountName: 'operate-workflow-sa'
  dependencies:
    - name: 'bucket-events'
      eventSourceName: 'aws-sqs-bucket-events'
      eventName: 'bucket-events'
  triggers:
    - template:
        name: 'trigger-wf-bucket-events'
        argoWorkflow:
          operation: 'submit'
          source:
            resource:
              apiVersion: 'argoproj.io/v1alpha1'
              kind: 'Workflow'
              metadata:
                generateName: 'test-print-'
                namespace: 'argo'
              spec:
                arguments:
                  parameters:
                    - name: 'message'
                      value: ''
                workflowTemplateRef:
                  name: 'test-print'
        parameters:
          - src:
              dependencyName: 'bucket-events'
              dataKey: 'body'
            dest: 'spec.arguments.parameters.0.value'
