// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface ElasticagentProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values: ElasticagentValues;
}

export class Elasticagent extends Construct {
  public constructor(scope: Construct, id: string, props: ElasticagentProps) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_ElasticagentValues(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'elastic-agent',
      repo: 'https://helm.elastic.co',
      version: '9.3.1',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      } else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * Schema for managing the Elastic Agent Helm chart values.
 *
 * @schema elastic-agent
 */
export interface ElasticagentValues {
  /**
   * Object containing multiple output configurations.
   *
   * @schema elastic-agent#outputs
   */
  readonly outputs: { [key: string]: OutputObject };

  /**
   * Configuration for system integration.
   *
   * @schema elastic-agent#system
   */
  readonly system?: ElasticAgentSystem;

  /**
   * Configuration for Kubernetes integration.
   *
   * @schema elastic-agent#kubernetes
   */
  readonly kubernetes?: ElasticAgentKubernetes;

  /**
   * Configuration for AutoOps integration.
   *
   * @schema elastic-agent#autoOps
   */
  readonly autoOps?: ElasticAgentAutoOps;

  /**
   * Configuration for extra integrations.
   *
   * @schema elastic-agent#extraIntegrations
   */
  readonly extraIntegrations?: { [key: string]: CustomIntegrationConfig };

  /**
   * Configuration for the Elastic-Agent.
   *
   * @schema elastic-agent#agent
   */
  readonly agent: ElasticAgentAgent;

  /**
   * @schema elastic-agent#kube-state-metrics
   */
  readonly kubeStateMetrics?: { [key: string]: any };

  /**
   * @schema elastic-agent#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema elastic-agent#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticagentValues' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticagentValues(obj: ElasticagentValues | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    outputs:
      obj.outputs === undefined
        ? undefined
        : Object.entries(obj.outputs).reduce(
            (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: toJson_OutputObject(i[1]) }),
            {},
          ),
    system: toJson_ElasticAgentSystem(obj.system),
    kubernetes: toJson_ElasticAgentKubernetes(obj.kubernetes),
    autoOps: toJson_ElasticAgentAutoOps(obj.autoOps),
    extraIntegrations:
      obj.extraIntegrations === undefined
        ? undefined
        : Object.entries(obj.extraIntegrations).reduce(
            (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: toJson_CustomIntegrationConfig(i[1]) }),
            {},
          ),
    agent: toJson_ElasticAgentAgent(obj.agent),
    'kube-state-metrics':
      obj.kubeStateMetrics === undefined
        ? undefined
        : Object.entries(obj.kubeStateMetrics).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
    global:
      obj.global === undefined
        ? undefined
        : Object.entries(obj.global).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Defines the configuration for an output.
 *
 * @schema OutputObject
 */
export interface OutputObject {
  /**
   * Type of the output.
   *
   * @schema OutputObject#type
   */
  readonly type: OutputObjectType;

  /**
   * hosts of the output (required for Logstash type).
   *
   * @schema OutputObject#hosts
   */
  readonly hosts?: any[];

  /**
   * URL of the output (required for ESPlainAuthBasic and ESPlainAuthAPI type).
   *
   * @schema OutputObject#url
   */
  readonly url?: string;

  /**
   * Username to authenticate with the output (required for ESPlainAuthBasic).
   *
   * @schema OutputObject#username
   */
  readonly username?: string;

  /**
   * Password to authenticate with the output (required for ESPlainAuthBasic).
   *
   * @schema OutputObject#password
   */
  readonly password?: string;

  /**
   * API key to authenticate with the output (required for ESPlainAuthAPI type).
   *
   * @schema OutputObject#api_key
   */
  readonly apiKey?: string;

  /**
   * K8s secret to mount output connection details (required for ESSecretAuthBasic and ESSecretAuthAPI types).
   *
   * @schema OutputObject#secretName
   */
  readonly secretName?: string;

  /**
   * Name to reference an Elasticsearch cluster managed by ECK (required for ESECKRef type).
   *
   * @schema OutputObject#name
   */
  readonly name?: string;

  /**
   * Namespace to reference an Elasticsearch cluster managed by ECK (optional for ESECKRef type).
   *
   * @schema OutputObject#namespace
   */
  readonly namespace?: string;

  /**
   * @schema OutputObject#ssl
   */
  readonly ssl?: SslConfigClient;

  /**
   * If true and multiple Logstash hosts are configured, the output plugin load balances published events onto all Logstash hosts. If false, the output plugin sends all events to one host (determined at random) and switches to another host if the selected one becomes unresponsive.
   *
   * @schema OutputObject#loadbalance
   */
  readonly loadbalance?: boolean;

  /**
   * Time to live for a connection to Logstash after which the connection will be reestablished. This setting is useful when Logstash hosts represent load balancers. Because connections to Logstash hosts are sticky, operating behind load balancers can lead to uneven load distribution across instances. Specify a TTL on the connection to achieve equal connection distribution across instances.
   *
   * @schema OutputObject#ttl
   */
  readonly ttl?: string;

  /**
   * If true, only a subset of events in a batch of events is transferred per transaction. The number of events to be sent increases up to bulk_max_size if no error is encountered. On error, the number of events per transaction is reduced again.
   *
   * @schema OutputObject#slow_start
   */
  readonly slowStart?: boolean;

  /**
   * The number of batches to send asynchronously to Logstash while waiting for an ACK from Logstash. The output becomes blocking after the specified number of batches are written. Specify 0 to turn off pipelining.
   *
   * @schema OutputObject#pipelining
   */
  readonly pipelining?: number;

  /**
   * Workers used to publish events. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#workers
   */
  readonly workers?: number;

  /**
   * The HTTP request timeout in seconds for the output request. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#timeout
   */
  readonly timeout?: string;

  /**
   * @schema OutputObject#queue
   */
  readonly queue?: OutputObjectQueue;

  /**
   * The number of times to retry publishing an event after a publishing failure. After the specified number of retries, the events are typically dropped. Set max_retries to a value less than 0 to retry until all events are published. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#max_retries
   */
  readonly maxRetries?: number;

  /**
   * The gzip compression level. Set this value to 0 to disable compression. The compression level must be in the range of 1 (best speed) to 9 (best compression). Increasing the compression level reduces network usage but increases CPU usage. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#compression_level
   */
  readonly compressionLevel?: number;

  /**
   * The maximum number of events to bulk in a single Elasticsearch bulk API index request. Events can be collected into batches. Elastic Agent will split batches larger than bulk_max_size into multiple batches. Specifying a larger batch size can improve performance by lowering the overhead of sending events. However big batch sizes can also increase processing times, which might result in API errors, killed connections, timed-out publishing requests, and, ultimately, lower throughput. Setting bulk_max_size to values less than or equal to 0 turns off the splitting of batches. When splitting is disabled, the queue decides on the number of events to be contained in a batch. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#bulk_max_size
   */
  readonly bulkMaxSize?: number;

  /**
   * @schema OutputObject#backoff
   */
  readonly backoff?: OutputObjectBackoff;

  /**
   * Allow Elastic Agent to connect and send output to an Elasticsearch instance that is running an earlier version than the agent version. Note that this setting does not affect Elastic Agent's ability to connect to Fleet Server. Fleet Server will not accept a connection from an agent at a later major or minor version. It will accept a connection from an agent at a later patch version. For example, an Elastic Agent at version 8.14.3 can connect to a Fleet Server on version 8.14.0, but an agent at version 8.15.0 or later is not able to connect. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObject#allow_older_versions
   */
  readonly allowOlderVersions?: boolean;
}

/**
 * Converts an object of type 'OutputObject' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_OutputObject(obj: OutputObject | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    type: obj.type,
    hosts: obj.hosts?.map((y) => y),
    url: obj.url,
    username: obj.username,
    password: obj.password,
    api_key: obj.apiKey,
    secretName: obj.secretName,
    name: obj.name,
    namespace: obj.namespace,
    ssl: toJson_SslConfigClient(obj.ssl),
    loadbalance: obj.loadbalance,
    ttl: obj.ttl,
    slow_start: obj.slowStart,
    pipelining: obj.pipelining,
    workers: obj.workers,
    timeout: obj.timeout,
    queue: toJson_OutputObjectQueue(obj.queue),
    max_retries: obj.maxRetries,
    compression_level: obj.compressionLevel,
    bulk_max_size: obj.bulkMaxSize,
    backoff: toJson_OutputObjectBackoff(obj.backoff),
    allow_older_versions: obj.allowOlderVersions,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for system integration.
 *
 * @schema ElasticAgentSystem
 */
export interface ElasticAgentSystem {
  /**
   * Enable system integration.
   *
   * @schema ElasticAgentSystem#enabled
   */
  readonly enabled: boolean;

  /**
   * Name of the output used in system integration. Must be defined in outputs.
   *
   * @schema ElasticAgentSystem#output
   */
  readonly output: string;

  /**
   * output namespace.
   *
   * @schema ElasticAgentSystem#namespace
   */
  readonly namespace?: string;

  /**
   * @schema ElasticAgentSystem#authLogs
   */
  readonly authLogs?: ElasticAgentSystemAuthLogs;

  /**
   * @schema ElasticAgentSystem#syslog
   */
  readonly syslog?: ElasticAgentSystemSyslog;

  /**
   * @schema ElasticAgentSystem#metrics
   */
  readonly metrics?: ElasticAgentSystemMetrics;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentSystem#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentSystem' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentSystem(obj: ElasticAgentSystem | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    output: obj.output,
    namespace: obj.namespace,
    authLogs: toJson_ElasticAgentSystemAuthLogs(obj.authLogs),
    syslog: toJson_ElasticAgentSystemSyslog(obj.syslog),
    metrics: toJson_ElasticAgentSystemMetrics(obj.metrics),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for Kubernetes integration.
 *
 * @schema ElasticAgentKubernetes
 */
export interface ElasticAgentKubernetes {
  /**
   * Enable Kubernetes integration.
   *
   * @schema ElasticAgentKubernetes#enabled
   */
  readonly enabled?: boolean;

  /**
   * Onboarding ID for quick-start flow.
   *
   * @schema ElasticAgentKubernetes#onboardingID
   */
  readonly onboardingId?: string;

  /**
   * Name of the output used in Kubernetes integration. Must be defined in outputs.
   *
   * @schema ElasticAgentKubernetes#output
   */
  readonly output?: string;

  /**
   * Kubernetes namespace.
   *
   * @schema ElasticAgentKubernetes#namespace
   */
  readonly namespace?: string;

  /**
   * @schema ElasticAgentKubernetes#hints
   */
  readonly hints?: ElasticAgentKubernetesHints;

  /**
   * @schema ElasticAgentKubernetes#state
   */
  readonly state?: ElasticAgentKubernetesState;

  /**
   * @schema ElasticAgentKubernetes#metrics
   */
  readonly metrics?: ElasticAgentKubernetesMetrics;

  /**
   * @schema ElasticAgentKubernetes#apiserver
   */
  readonly apiserver?: ElasticAgentKubernetesApiserver;

  /**
   * @schema ElasticAgentKubernetes#proxy
   */
  readonly proxy?: ElasticAgentKubernetesProxy;

  /**
   * @schema ElasticAgentKubernetes#scheduler
   */
  readonly scheduler?: ElasticAgentKubernetesScheduler;

  /**
   * @schema ElasticAgentKubernetes#controller_manager
   */
  readonly controllerManager?: ElasticAgentKubernetesControllerManager;

  /**
   * @schema ElasticAgentKubernetes#containers
   */
  readonly containers?: ElasticAgentKubernetesContainers;

  /**
   * @schema ElasticAgentKubernetes#pods
   */
  readonly pods?: KubernetesMetricsAndStateConfig;

  /**
   * @schema ElasticAgentKubernetes#deployments
   */
  readonly deployments?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#statefulsets
   */
  readonly statefulsets?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#daemonsets
   */
  readonly daemonsets?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#replicasets
   */
  readonly replicasets?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#namespaces
   */
  readonly namespaces?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#volumes
   */
  readonly volumes?: KubernetesMetricsConfig;

  /**
   * @schema ElasticAgentKubernetes#nodes
   */
  readonly nodes?: KubernetesMetricsAndStateConfig;

  /**
   * @schema ElasticAgentKubernetes#storageclasses
   */
  readonly storageclasses?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#jobs
   */
  readonly jobs?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#cronjobs
   */
  readonly cronjobs?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#persistentvolumes
   */
  readonly persistentvolumes?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#persistentvolumeclaims
   */
  readonly persistentvolumeclaims?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#resourcequotas
   */
  readonly resourcequotas?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#services
   */
  readonly services?: KubernetesStateConfig;

  /**
   * @schema ElasticAgentKubernetes#system
   */
  readonly system?: KubernetesMetricsConfig;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetes#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetes' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetes(
  obj: ElasticAgentKubernetes | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    onboardingID: obj.onboardingId,
    output: obj.output,
    namespace: obj.namespace,
    hints: toJson_ElasticAgentKubernetesHints(obj.hints),
    state: toJson_ElasticAgentKubernetesState(obj.state),
    metrics: toJson_ElasticAgentKubernetesMetrics(obj.metrics),
    apiserver: toJson_ElasticAgentKubernetesApiserver(obj.apiserver),
    proxy: toJson_ElasticAgentKubernetesProxy(obj.proxy),
    scheduler: toJson_ElasticAgentKubernetesScheduler(obj.scheduler),
    controller_manager: toJson_ElasticAgentKubernetesControllerManager(obj.controllerManager),
    containers: toJson_ElasticAgentKubernetesContainers(obj.containers),
    pods: toJson_KubernetesMetricsAndStateConfig(obj.pods),
    deployments: toJson_KubernetesStateConfig(obj.deployments),
    statefulsets: toJson_KubernetesStateConfig(obj.statefulsets),
    daemonsets: toJson_KubernetesStateConfig(obj.daemonsets),
    replicasets: toJson_KubernetesStateConfig(obj.replicasets),
    namespaces: toJson_KubernetesStateConfig(obj.namespaces),
    volumes: toJson_KubernetesMetricsConfig(obj.volumes),
    nodes: toJson_KubernetesMetricsAndStateConfig(obj.nodes),
    storageclasses: toJson_KubernetesStateConfig(obj.storageclasses),
    jobs: toJson_KubernetesStateConfig(obj.jobs),
    cronjobs: toJson_KubernetesStateConfig(obj.cronjobs),
    persistentvolumes: toJson_KubernetesStateConfig(obj.persistentvolumes),
    persistentvolumeclaims: toJson_KubernetesStateConfig(obj.persistentvolumeclaims),
    resourcequotas: toJson_KubernetesStateConfig(obj.resourcequotas),
    services: toJson_KubernetesStateConfig(obj.services),
    system: toJson_KubernetesMetricsConfig(obj.system),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for AutoOps integration.
 *
 * @schema ElasticAgentAutoOps
 */
export interface ElasticAgentAutoOps {
  /**
   * Enable AutoOps integration.
   *
   * @schema ElasticAgentAutoOps#enabled
   */
  readonly enabled?: boolean;

  /**
   * Token to register into AutoOps
   *
   * @schema ElasticAgentAutoOps#autoops_token
   */
  readonly autoopsToken?: string;

  /**
   * OTel server URL
   *
   * @schema ElasticAgentAutoOps#autoops_otel_url
   */
  readonly autoopsOtelUrl?: string;

  /**
   * Temporary resource ID
   *
   * @schema ElasticAgentAutoOps#autoops_temp_resource_id
   */
  readonly autoopsTempResourceId?: string;

  /**
   * Monitored ES cluster API key
   *
   * @schema ElasticAgentAutoOps#es_api_key
   */
  readonly esApiKey?: string;

  /**
   * Monitored ES cluster username
   *
   * @schema ElasticAgentAutoOps#es_username
   */
  readonly esUsername?: string;

  /**
   * Monitored ES cluster password
   *
   * @schema ElasticAgentAutoOps#es_password
   */
  readonly esPassword?: string;

  /**
   * Monitored ES cluster URL
   *
   * @schema ElasticAgentAutoOps#autoops_es_url
   */
  readonly autoopsEsUrl?: string;

  /**
   * Cloud Connected Mode API key
   *
   * @schema ElasticAgentAutoOps#elastic_cloud_connected_mode_api_key
   */
  readonly elasticCloudConnectedModeApiKey?: string;

  /**
   * Cloud Connected Mode API URL
   *
   * @schema ElasticAgentAutoOps#elastic_cloud_connected_mode_api_url
   */
  readonly elasticCloudConnectedModeApiUrl?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentAutoOps#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentAutoOps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentAutoOps(obj: ElasticAgentAutoOps | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    autoops_token: obj.autoopsToken,
    autoops_otel_url: obj.autoopsOtelUrl,
    autoops_temp_resource_id: obj.autoopsTempResourceId,
    es_api_key: obj.esApiKey,
    es_username: obj.esUsername,
    es_password: obj.esPassword,
    autoops_es_url: obj.autoopsEsUrl,
    elastic_cloud_connected_mode_api_key: obj.elasticCloudConnectedModeApiKey,
    elastic_cloud_connected_mode_api_url: obj.elasticCloudConnectedModeApiUrl,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for a single integration.
 *
 * @schema CustomIntegrationConfig
 */
export interface CustomIntegrationConfig {
  /**
   * Unique identifier for the integration.
   *
   * @schema CustomIntegrationConfig#id
   */
  readonly id: string;

  /**
   * Agent preset that this integration runs on.
   *
   * @schema CustomIntegrationConfig#preset
   */
  readonly preset: string;

  /**
   * Name of the output to use.
   *
   * @schema CustomIntegrationConfig#use_output
   */
  readonly useOutput: string;
}

/**
 * Converts an object of type 'CustomIntegrationConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_CustomIntegrationConfig(
  obj: CustomIntegrationConfig | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    id: obj.id,
    preset: obj.preset,
    use_output: obj.useOutput,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for the Elastic-Agent.
 *
 * @schema ElasticAgentAgent
 */
export interface ElasticAgentAgent {
  /**
   * Elastic-Agent version.
   *
   * @schema ElasticAgentAgent#version
   */
  readonly version: string;

  /**
   * @schema ElasticAgentAgent#image
   */
  readonly image?: AgentImageConfig;

  /**
   * @schema ElasticAgentAgent#imagePullSecrets
   */
  readonly imagePullSecrets?: any[];

  /**
   * Engine to use for Kubernetes manifests or ECK CRDs.
   *
   * @schema ElasticAgentAgent#engine
   */
  readonly engine: ElasticAgentAgentEngine;

  /**
   * Enable unprivileged mode.
   *
   * @schema ElasticAgentAgent#unprivileged
   */
  readonly unprivileged?: boolean;

  /**
   * Elastic-Agent managed configuration.
   *
   * @schema ElasticAgentAgent#fleet
   */
  readonly fleet?: ElasticAgentAgentFleet;

  /**
   * Map of deployment presets for the Elastic Agent.
   *
   * @schema ElasticAgentAgent#presets
   */
  readonly presets: { [key: string]: AgentPreset };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentAgent#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentAgent' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentAgent(obj: ElasticAgentAgent | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    version: obj.version,
    image: toJson_AgentImageConfig(obj.image),
    imagePullSecrets: obj.imagePullSecrets?.map((y) => y),
    engine: obj.engine,
    unprivileged: obj.unprivileged,
    fleet: toJson_ElasticAgentAgentFleet(obj.fleet),
    presets:
      obj.presets === undefined
        ? undefined
        : Object.entries(obj.presets).reduce(
            (r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: toJson_AgentPreset(i[1]) }),
            {},
          ),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Type of the output.
 *
 * @schema OutputObjectType
 */
export enum OutputObjectType {
  /** ESPlainAuthBasic */
  ES_PLAIN_AUTH_BASIC = 'ESPlainAuthBasic',
  /** ESPlainAuthAPI */
  ES_PLAIN_AUTH_API = 'ESPlainAuthAPI',
  /** ESSecretAuthBasic */
  ES_SECRET_AUTH_BASIC = 'ESSecretAuthBasic',
  /** ESSecretAuthAPI */
  ES_SECRET_AUTH_API = 'ESSecretAuthAPI',
  /** ESECKRef */
  ESECK_REF = 'ESECKRef',
  /** Logstash */
  LOGSTASH = 'Logstash',
}

/**
 * @schema SSLConfigClient
 */
export interface SslConfigClient {
  /**
   * Enables or disables the SSL configuration.
   *
   * @schema SSLConfigClient#enabled
   */
  readonly enabled?: boolean;

  /**
   * The list of root certificates for verifications (required). If certificate_authorities is empty or not set, the system keystore is used. If certificate_authorities is self-signed, the host system needs to trust that CA cert as well.
   *
   * @schema SSLConfigClient#certificateAuthorities
   */
  readonly certificateAuthorities?: ValueFrom[];

  /**
   * The certificates for mtls verifications(Logstash Only).
   *
   * @schema SSLConfigClient#certificate
   */
  readonly certificate?: ValueFrom;

  /**
   * The key for mtls verifications(Logstash Only).
   *
   * @schema SSLConfigClient#key
   */
  readonly key?: ValueFrom;

  /**
   * The key passphrase for mtls verifications(Logstash Only).
   *
   * @schema SSLConfigClient#key_passphrase
   */
  readonly keyPassphrase?: ValueFrom;

  /**
   * Configures the type of TLS renegotiation to support.
   *
   * @schema SSLConfigClient#renegotiation
   */
  readonly renegotiation?: SslConfigClientRenegotiation;

  /**
   * Controls the verification of server certificates.
   *
   * @schema SSLConfigClient#verificationMode
   */
  readonly verificationMode?: SslConfigClientVerificationMode;

  /**
   * Configures client authentication.
   *
   * @schema SSLConfigClient#client_authentication
   */
  readonly clientAuthentication?: SslConfigClientClientAuthentication;

  /**
   * The list of cipher suites to use. The first entry has the highest priority. If this option is omitted, the Go crypto library’s default suites are used (recommended). Note that TLS 1.3 cipher suites are not individually configurable in Go, so they are not included in this list.
   *
   * @schema SSLConfigClient#cipher_suites
   */
  readonly cipherSuites?: any[];

  /**
   * The list of curve types for ECDHE (Elliptic Curve Diffie-Hellman ephemeral key exchange).
   *
   * @schema SSLConfigClient#curve_types
   */
  readonly curveTypes?: any[];

  /**
   * List of allowed SSL/TLS versions. If the SSL/TLS server supports none of the specified versions, the connection will be dropped during or after the handshake. The list of allowed protocol versions include: TLSv1.1, TLSv1.2, and TLSv1.3.
   *
   * @schema SSLConfigClient#supported_protocols
   */
  readonly supportedProtocols?: any[];

  /**
   * This configures a certificate pin that you can use to ensure that a specific certificate is part of the verified chain.
   *
   * @schema SSLConfigClient#ca_sha256
   */
  readonly caSha256?: string;

  /**
   * A HEX encoded SHA-256 of a CA certificate. If this certificate is present in the chain during the handshake, it will be added to the certificate_authorities list and the handshake will continue normally.
   *
   * @schema SSLConfigClient#caTrustedFingerprint
   */
  readonly caTrustedFingerprint?: string;
}

/**
 * Converts an object of type 'SslConfigClient' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_SslConfigClient(obj: SslConfigClient | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    certificateAuthorities: obj.certificateAuthorities?.map((y) => toJson_ValueFrom(y)),
    certificate: toJson_ValueFrom(obj.certificate),
    key: toJson_ValueFrom(obj.key),
    key_passphrase: toJson_ValueFrom(obj.keyPassphrase),
    renegotiation: obj.renegotiation,
    verificationMode: obj.verificationMode,
    client_authentication: obj.clientAuthentication,
    cipher_suites: obj.cipherSuites?.map((y) => y),
    curve_types: obj.curveTypes?.map((y) => y),
    supported_protocols: obj.supportedProtocols?.map((y) => y),
    ca_sha256: obj.caSha256,
    caTrustedFingerprint: obj.caTrustedFingerprint,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema OutputObjectQueue
 */
export interface OutputObjectQueue {
  /**
   * @schema OutputObjectQueue#mem
   */
  readonly mem?: OutputObjectQueueMem;
}

/**
 * Converts an object of type 'OutputObjectQueue' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_OutputObjectQueue(obj: OutputObjectQueue | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    mem: toJson_OutputObjectQueueMem(obj.mem),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema OutputObjectBackoff
 */
export interface OutputObjectBackoff {
  /**
   * The maximum number of seconds to wait before attempting to connect to Elasticsearch after a network error. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObjectBackoff#max
   */
  readonly max?: string;

  /**
   * The number of seconds to wait before trying to reconnect to Elasticsearch after a network error. After waiting backoff.init seconds, Elastic Agent tries to reconnect. If the attempt fails, the backoff timer is increased exponentially up to backoff.max. After a successful connection, the backoff timer is reset. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObjectBackoff#init
   */
  readonly init?: string;
}

/**
 * Converts an object of type 'OutputObjectBackoff' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_OutputObjectBackoff(obj: OutputObjectBackoff | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    max: obj.max,
    init: obj.init,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentSystemAuthLogs
 */
export interface ElasticAgentSystemAuthLogs {
  /**
   * Enable system auth logs stream.
   *
   * @schema ElasticAgentSystemAuthLogs#enabled
   */
  readonly enabled: boolean;

  /**
   * @schema ElasticAgentSystemAuthLogs#vars
   */
  readonly vars?: SystemLogsStreamVars;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentSystemAuthLogs#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentSystemAuthLogs' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentSystemAuthLogs(
  obj: ElasticAgentSystemAuthLogs | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: toJson_SystemLogsStreamVars(obj.vars),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentSystemSyslog
 */
export interface ElasticAgentSystemSyslog {
  /**
   * Enable system syslog stream.
   *
   * @schema ElasticAgentSystemSyslog#enabled
   */
  readonly enabled: boolean;

  /**
   * @schema ElasticAgentSystemSyslog#vars
   */
  readonly vars?: SystemLogsStreamVars;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentSystemSyslog#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentSystemSyslog' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentSystemSyslog(
  obj: ElasticAgentSystemSyslog | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: toJson_SystemLogsStreamVars(obj.vars),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentSystemMetrics
 */
export interface ElasticAgentSystemMetrics {
  /**
   * Enable system metrics stream.
   *
   * @schema ElasticAgentSystemMetrics#enabled
   */
  readonly enabled: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentSystemMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentSystemMetrics' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentSystemMetrics(
  obj: ElasticAgentSystemMetrics | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesHints
 */
export interface ElasticAgentKubernetesHints {
  /**
   * Enable elastic-agent autodiscovery feature.
   *
   * @schema ElasticAgentKubernetesHints#enabled
   */
  readonly enabled?: boolean;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesHints#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesHints' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesHints(
  obj: ElasticAgentKubernetesHints | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesState
 */
export interface ElasticAgentKubernetesState {
  /**
   * Enable state streams based on kube-state-metrics.
   *
   * @schema ElasticAgentKubernetesState#enabled
   */
  readonly enabled: boolean;

  /**
   * Host of the kube-state-metrics service, used when kube-state-metrics.enabled is set to false.
   *
   * @schema ElasticAgentKubernetesState#host
   */
  readonly host?: string;

  /**
   * State streams variables.
   *
   * @schema ElasticAgentKubernetesState#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesState#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesState' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesState(
  obj: ElasticAgentKubernetesState | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    host: obj.host,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesMetrics
 */
export interface ElasticAgentKubernetesMetrics {
  /**
   * Enable metric streams based on kubelet.
   *
   * @schema ElasticAgentKubernetesMetrics#enabled
   */
  readonly enabled: boolean;

  /**
   * Metric streams variables.
   *
   * @schema ElasticAgentKubernetesMetrics#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesMetrics#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesMetrics' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesMetrics(
  obj: ElasticAgentKubernetesMetrics | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesApiserver
 */
export interface ElasticAgentKubernetesApiserver {
  /**
   * Enable apiserver input.
   *
   * @schema ElasticAgentKubernetesApiserver#enabled
   */
  readonly enabled: boolean;

  /**
   * Apiserver variables.
   *
   * @schema ElasticAgentKubernetesApiserver#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesApiserver#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesApiserver' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesApiserver(
  obj: ElasticAgentKubernetesApiserver | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesProxy
 */
export interface ElasticAgentKubernetesProxy {
  /**
   * Enable proxy input.
   *
   * @schema ElasticAgentKubernetesProxy#enabled
   */
  readonly enabled: boolean;

  /**
   * Proxy stream variables.
   *
   * @schema ElasticAgentKubernetesProxy#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesProxy#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesProxy' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesProxy(
  obj: ElasticAgentKubernetesProxy | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesScheduler
 */
export interface ElasticAgentKubernetesScheduler {
  /**
   * Enable scheduler input.
   *
   * @schema ElasticAgentKubernetesScheduler#enabled
   */
  readonly enabled: boolean;

  /**
   * Scheduler stream variables.
   *
   * @schema ElasticAgentKubernetesScheduler#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesScheduler#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesScheduler' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesScheduler(
  obj: ElasticAgentKubernetesScheduler | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesControllerManager
 */
export interface ElasticAgentKubernetesControllerManager {
  /**
   * Enable controller_manager input.
   *
   * @schema ElasticAgentKubernetesControllerManager#enabled
   */
  readonly enabled: boolean;

  /**
   * Controller manager stream variables.
   *
   * @schema ElasticAgentKubernetesControllerManager#vars
   */
  readonly vars?: any;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesControllerManager#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesControllerManager' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesControllerManager(
  obj: ElasticAgentKubernetesControllerManager | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesContainers
 */
export interface ElasticAgentKubernetesContainers {
  /**
   * @schema ElasticAgentKubernetesContainers#metrics
   */
  readonly metrics?: KubernetesStreamConfig;

  /**
   * @schema ElasticAgentKubernetesContainers#state
   */
  readonly state?: KubernetesStreamConfig;

  /**
   * @schema ElasticAgentKubernetesContainers#logs
   */
  readonly logs?: ElasticAgentKubernetesContainersLogs;

  /**
   * @schema ElasticAgentKubernetesContainers#audit_logs
   */
  readonly auditLogs?: KubernetesStreamConfig;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesContainers#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesContainers' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesContainers(
  obj: ElasticAgentKubernetesContainers | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    metrics: toJson_KubernetesStreamConfig(obj.metrics),
    state: toJson_KubernetesStreamConfig(obj.state),
    logs: toJson_ElasticAgentKubernetesContainersLogs(obj.logs),
    audit_logs: toJson_KubernetesStreamConfig(obj.auditLogs),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema KubernetesMetricsAndStateConfig
 */
export interface KubernetesMetricsAndStateConfig {
  /**
   * @schema KubernetesMetricsAndStateConfig#metrics
   */
  readonly metrics?: KubernetesStreamConfig;

  /**
   * @schema KubernetesMetricsAndStateConfig#state
   */
  readonly state?: KubernetesStreamConfig;
}

/**
 * Converts an object of type 'KubernetesMetricsAndStateConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_KubernetesMetricsAndStateConfig(
  obj: KubernetesMetricsAndStateConfig | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    metrics: toJson_KubernetesStreamConfig(obj.metrics),
    state: toJson_KubernetesStreamConfig(obj.state),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema KubernetesStateConfig
 */
export interface KubernetesStateConfig {
  /**
   * @schema KubernetesStateConfig#state
   */
  readonly state?: KubernetesStreamConfig;
}

/**
 * Converts an object of type 'KubernetesStateConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_KubernetesStateConfig(obj: KubernetesStateConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    state: toJson_KubernetesStreamConfig(obj.state),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema KubernetesMetricsConfig
 */
export interface KubernetesMetricsConfig {
  /**
   * @schema KubernetesMetricsConfig#metrics
   */
  readonly metrics?: KubernetesStreamConfig;
}

/**
 * Converts an object of type 'KubernetesMetricsConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_KubernetesMetricsConfig(
  obj: KubernetesMetricsConfig | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    metrics: toJson_KubernetesStreamConfig(obj.metrics),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Image configuration for the Elastic-Agent.
 *
 * @schema AgentImageConfig
 */
export interface AgentImageConfig {
  /**
   * Docker image repository.
   *
   * @schema AgentImageConfig#repository
   */
  readonly repository: string;

  /**
   * Image pull policy.
   *
   * @schema AgentImageConfig#pullPolicy
   */
  readonly pullPolicy: AgentImageConfigPullPolicy;

  /**
   * Image tag.
   *
   * @schema AgentImageConfig#tag
   */
  readonly tag: string;
}

/**
 * Converts an object of type 'AgentImageConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentImageConfig(obj: AgentImageConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    repository: obj.repository,
    pullPolicy: obj.pullPolicy,
    tag: obj.tag,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Engine to use for Kubernetes manifests or ECK CRDs.
 *
 * @schema ElasticAgentAgentEngine
 */
export enum ElasticAgentAgentEngine {
  /** k8s */
  K8S = 'k8s',
  /** eck */
  ECK = 'eck',
}

/**
 * Elastic-Agent managed configuration.
 *
 * @schema ElasticAgentAgentFleet
 */
export interface ElasticAgentAgentFleet {
  /**
   * Enable Elastic-Agent managed mode.
   *
   * @schema ElasticAgentAgentFleet#enabled
   */
  readonly enabled: boolean;

  /**
   * CA certificate to use when connecting to Fleet.
   *
   * @schema ElasticAgentAgentFleet#ca
   */
  readonly ca?: ValueFrom;

  /**
   * Elastic Agent client certificate to use with Fleet Server during mTLS authentication.
   *
   * @schema ElasticAgentAgentFleet#force
   */
  readonly force?: boolean;

  /**
   * Elastic Agent client private key to use with Fleet Server during mTLS authentication.
   *
   * @schema ElasticAgentAgentFleet#agentCert
   */
  readonly agentCert?: ValueFrom;

  /**
   * Elastic Agent client private key to use with Fleet Server during mTLS authentication.
   *
   * @schema ElasticAgentAgentFleet#agentCertKey
   */
  readonly agentCertKey?: ValueFrom;

  /**
   * CA certificate to use when connecting to Kibana if the enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#kibanaCA
   */
  readonly kibanaCa?: ValueFrom;

  /**
   * Service token to use when connecting to Kibana if the enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#kibanaServiceToken
   */
  readonly kibanaServiceToken?: string;

  /**
   * Token name to use for fetching token from Kibana if the enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#tokenName
   */
  readonly tokenName?: string;

  /**
   * Token policy name to use for fetching token from Kibana if the enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#policyName
   */
  readonly policyName?: string;

  /**
   * Fleet server URL.
   *
   * @schema ElasticAgentAgentFleet#url
   */
  readonly url?: string;

  /**
   * Fleet enrollment token.
   *
   * @schema ElasticAgentAgentFleet#token
   */
  readonly token?: string;

  /**
   * Communicate with Fleet with either insecure HTTP or unverified HTTPS.
   *
   * @schema ElasticAgentAgentFleet#insecure
   */
  readonly insecure?: boolean;

  /**
   * Kibana host to fallback if enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#kibanaHost
   */
  readonly kibanaHost?: string;

  /**
   * Kibana username to fallback if enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#kibanaUser
   */
  readonly kibanaUser?: string;

  /**
   * Kibana password to fallback if enrollment token is not supplied.
   *
   * @schema ElasticAgentAgentFleet#kibanaPassword
   */
  readonly kibanaPassword?: string;

  /**
   * Agent preset to deploy.
   *
   * @schema ElasticAgentAgentFleet#preset
   */
  readonly preset?: string;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentAgentFleet#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentAgentFleet' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentAgentFleet(
  obj: ElasticAgentAgentFleet | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    ca: toJson_ValueFrom(obj.ca),
    force: obj.force,
    agentCert: toJson_ValueFrom(obj.agentCert),
    agentCertKey: toJson_ValueFrom(obj.agentCertKey),
    kibanaCA: toJson_ValueFrom(obj.kibanaCa),
    kibanaServiceToken: obj.kibanaServiceToken,
    tokenName: obj.tokenName,
    policyName: obj.policyName,
    url: obj.url,
    token: obj.token,
    insecure: obj.insecure,
    kibanaHost: obj.kibanaHost,
    kibanaUser: obj.kibanaUser,
    kibanaPassword: obj.kibanaPassword,
    preset: obj.preset,
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configuration for an Agent preset.
 *
 * @schema AgentPreset
 */
export interface AgentPreset {
  /**
   * Mode of the Agent preset.
   *
   * @schema AgentPreset#mode
   */
  readonly mode: AgentPresetMode;

  /**
   * Replica count for the preset.
   *
   * @schema AgentPreset#replicaCount
   */
  readonly replicaCount?: number;

  /**
   * Labels for the deployment.
   *
   * @schema AgentPreset#labels
   */
  readonly labels?: { [key: string]: string };

  /**
   * Annotations for the deployment.
   *
   * @schema AgentPreset#annotations
   */
  readonly annotations?: { [key: string]: string };

  /**
   * Command for the container.
   *
   * @schema AgentPreset#command
   */
  readonly command?: string[];

  /**
   * Arguments for the container command.
   *
   * @schema AgentPreset#args
   */
  readonly args?: string[];

  /**
   * OpenTelemetry configuration.
   *
   * @schema AgentPreset#otelConfig
   */
  readonly otelConfig?: any;

  /**
   * Service configuration.
   *
   * @schema AgentPreset#service
   */
  readonly service?: AgentPresetService;

  /**
   * Port configuration.
   *
   * @schema AgentPreset#ports
   */
  readonly ports?: AgentPresetPorts[];

  /**
   * Affinity rules for the deployment.
   *
   * @schema AgentPreset#affinity
   */
  readonly affinity?: any;

  /**
   * Init containers for the deployment.
   *
   * @schema AgentPreset#initContainers
   */
  readonly initContainers?: any[];

  /**
   * Extra containers for the deployment.
   *
   * @schema AgentPreset#extraContainers
   */
  readonly extraContainers?: any[];

  /**
   * Automount service account token for the deployment.
   *
   * @schema AgentPreset#automountServiceAccountToken
   */
  readonly automountServiceAccountToken?: boolean;

  /**
   * Enable host networking for the deployment.
   *
   * @schema AgentPreset#hostNetwork
   */
  readonly hostNetwork?: boolean;

  /**
   * Enable host PID namespace for the deployment.
   *
   * @schema AgentPreset#hostPID
  readonly hostPid?: boolean;

  /**
   * Resource limits and requests for the deployment.
   *
   * @schema AgentPreset#resources
   */
  readonly resources?: any;

  /**
   * Security context for the deployment.
   *
   * @schema AgentPreset#securityContext
   */
  readonly securityContext?: any;

  /**
   * @schema AgentPreset#serviceAccount
   */
  readonly serviceAccount: AgentPresetServiceAccount;

  /**
   * @schema AgentPreset#clusterRole
   */
  readonly clusterRole: AgentPresetClusterRole;

  /**
   * @schema AgentPreset#priorityClass
   */
  readonly priorityClass?: AgentPriorityClass;

  /**
   * Environment variables for the deployment.
   *
   * @schema AgentPreset#envFrom
   */
  readonly envFrom?: any[];

  /**
   * Node selector for the deployment.
   *
   * @schema AgentPreset#nodeSelector
   */
  readonly nodeSelector?: { [key: string]: string };

  /**
   * Tolerations for the deployment.
   *
   * @schema AgentPreset#tolerations
   */
  readonly tolerations?: any[];

  /**
   * Topology spread constraints for the deployment.
   *
   * @schema AgentPreset#topologySpreadConstraints
   */
  readonly topologySpreadConstraints?: any[];

  /**
   * Extra environment variables for the deployment.
   *
   * @schema AgentPreset#extraEnvs
   */
  readonly extraEnvs?: any[];

  /**
   * Volume type used for Agent state persistence.
   *
   * @schema AgentPreset#statePersistence
   */
  readonly statePersistence?: AgentPresetStatePersistence;

  /**
   * Extra volumes for the deployment.
   *
   * @schema AgentPreset#extraVolumes
   */
  readonly extraVolumes?: any[];

  /**
   * Extra volume mounts for the deployment.
   *
   * @schema AgentPreset#extraVolumeMounts
   */
  readonly extraVolumeMounts?: any[];

  /**
   * @schema AgentPreset#agent
   */
  readonly agent?: AgentPresetAgent;

  /**
   * Providers configuration for the deployment.
   *
   * @schema AgentPreset#providers
   */
  readonly providers?: AgentPresetProviders;
}

/**
 * Converts an object of type 'AgentPreset' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPreset(obj: AgentPreset | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    mode: obj.mode,
    replicaCount: obj.replicaCount,
    labels:
      obj.labels === undefined
        ? undefined
        : Object.entries(obj.labels).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
    annotations:
      obj.annotations === undefined
        ? undefined
        : Object.entries(obj.annotations).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
    command: obj.command?.map((y) => y),
    args: obj.args?.map((y) => y),
    otelConfig: obj.otelConfig,
    service: toJson_AgentPresetService(obj.service),
    ports: obj.ports?.map((y) => toJson_AgentPresetPorts(y)),
    affinity: obj.affinity,
    initContainers: obj.initContainers?.map((y) => y),
    extraContainers: obj.extraContainers?.map((y) => y),
    automountServiceAccountToken: obj.automountServiceAccountToken,
    hostNetwork: obj.hostNetwork,
    hostPID: obj.hostPid,
    resources: obj.resources,
    securityContext: obj.securityContext,
    serviceAccount: toJson_AgentPresetServiceAccount(obj.serviceAccount),
    clusterRole: toJson_AgentPresetClusterRole(obj.clusterRole),
    priorityClass: toJson_AgentPriorityClass(obj.priorityClass),
    envFrom: obj.envFrom?.map((y) => y),
    nodeSelector:
      obj.nodeSelector === undefined
        ? undefined
        : Object.entries(obj.nodeSelector).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
    tolerations: obj.tolerations?.map((y) => y),
    topologySpreadConstraints: obj.topologySpreadConstraints?.map((y) => y),
    extraEnvs: obj.extraEnvs?.map((y) => y),
    statePersistence: obj.statePersistence,
    extraVolumes: obj.extraVolumes?.map((y) => y),
    extraVolumeMounts: obj.extraVolumeMounts?.map((y) => y),
    agent: toJson_AgentPresetAgent(obj.agent),
    providers: toJson_AgentPresetProviders(obj.providers),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ValueFrom
 */
export interface ValueFrom {
  /**
   * @schema ValueFrom#value
   */
  readonly value?: string;

  /**
   * @schema ValueFrom#valueFromSecret
   */
  readonly valueFromSecret?: ValueFromValueFromSecret;
}

/**
 * Converts an object of type 'ValueFrom' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ValueFrom(obj: ValueFrom | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    value: obj.value,
    valueFromSecret: toJson_ValueFromValueFromSecret(obj.valueFromSecret),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configures the type of TLS renegotiation to support.
 *
 * @schema SslConfigClientRenegotiation
 */
export enum SslConfigClientRenegotiation {
  /** never */
  NEVER = 'never',
  /** once */
  ONCE = 'once',
  /** freely */
  FREELY = 'freely',
}

/**
 * Controls the verification of server certificates.
 *
 * @schema SslConfigClientVerificationMode
 */
export enum SslConfigClientVerificationMode {
  /** full */
  FULL = 'full',
  /** strict */
  STRICT = 'strict',
  /** certificate */
  CERTIFICATE = 'certificate',
  /** none */
  NONE = 'none',
}

/**
 * Configures client authentication.
 *
 * @schema SslConfigClientClientAuthentication
 */
export enum SslConfigClientClientAuthentication {
  /** none */
  NONE = 'none',
  /** optional */
  OPTIONAL = 'optional',
  /** required */
  REQUIRED = 'required',
}

/**
 * @schema OutputObjectQueueMem
 */
export interface OutputObjectQueueMem {
  /**
   * @schema OutputObjectQueueMem#flush
   */
  readonly flush?: OutputObjectQueueMemFlush;

  /**
   * The number of events the queue can store. This value should be evenly divisible by the smaller of queue.mem.flush.min_events or bulk_max_size to avoid sending partial batches to the output. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObjectQueueMem#events
   */
  readonly events?: number;
}

/**
 * Converts an object of type 'OutputObjectQueueMem' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_OutputObjectQueueMem(obj: OutputObjectQueueMem | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    flush: toJson_OutputObjectQueueMemFlush(obj.flush),
    events: obj.events,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * System integration log stream variables.
 *
 * @schema SystemLogsStreamVars
 */
export interface SystemLogsStreamVars {
  /**
   * Paths to scan for logs.
   *
   * @schema SystemLogsStreamVars#paths
   */
  readonly paths?: string[];

  /**
   * Files to exclude from logs.
   *
   * @schema SystemLogsStreamVars#exclude_files
   */
  readonly excludeFiles?: string[];

  /**
   * Processors for the system auth logs stream.
   *
   * @schema SystemLogsStreamVars#processors
   */
  readonly processors?: any[];

  /**
   * Tags for the logs stream.
   *
   * @schema SystemLogsStreamVars#tags
   */
  readonly tags?: string[];

  /**
   * If this option is specified, events that are older than the specified amount of time are ignored. Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
   *
   * @schema SystemLogsStreamVars#ignore_older
   */
  readonly ignoreOlder?: string;
}

/**
 * Converts an object of type 'SystemLogsStreamVars' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_SystemLogsStreamVars(obj: SystemLogsStreamVars | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    paths: obj.paths?.map((y) => y),
    exclude_files: obj.excludeFiles?.map((y) => y),
    processors: obj.processors?.map((y) => y),
    tags: obj.tags?.map((y) => y),
    ignore_older: obj.ignoreOlder,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema KubernetesStreamConfig
 */
export interface KubernetesStreamConfig {
  /**
   * Enable stream.
   *
   * @schema KubernetesStreamConfig#enabled
   */
  readonly enabled: boolean;

  /**
   * Stream variables.
   *
   * @schema KubernetesStreamConfig#vars
   */
  readonly vars?: any;
}

/**
 * Converts an object of type 'KubernetesStreamConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_KubernetesStreamConfig(
  obj: KubernetesStreamConfig | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    vars: obj.vars,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ElasticAgentKubernetesContainersLogs
 */
export interface ElasticAgentKubernetesContainersLogs {
  /**
   * Enable containers logs stream.
   *
   * @schema ElasticAgentKubernetesContainersLogs#enabled
   */
  readonly enabled: boolean;

  /**
   * enable rotated logs ingestion. WARNING: enabling it might cause data re-ingestion on existing deployments. [ref](https://www.elastic.co/docs/reference/integrations/kubernetes/container-logs#ingesting-rotated-container-logs).
   *
   * @schema ElasticAgentKubernetesContainersLogs#rotated_logs
   */
  readonly rotatedLogs?: boolean;

  /**
   * Stream variables.
   *
   * @schema ElasticAgentKubernetesContainersLogs#vars
   */
  readonly vars?: ElasticAgentKubernetesContainersLogsVars;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesContainersLogs#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesContainersLogs' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesContainersLogs(
  obj: ElasticAgentKubernetesContainersLogs | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    rotated_logs: obj.rotatedLogs,
    vars: toJson_ElasticAgentKubernetesContainersLogsVars(obj.vars),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Image pull policy.
 *
 * @schema AgentImageConfigPullPolicy
 */
export enum AgentImageConfigPullPolicy {
  /** Always */
  ALWAYS = 'Always',
  /** IfNotPresent */
  IF_NOT_PRESENT = 'IfNotPresent',
  /** Never */
  NEVER = 'Never',
}

/**
 * Mode of the Agent preset.
 *
 * @schema AgentPresetMode
 */
export enum AgentPresetMode {
  /** deployment */
  DEPLOYMENT = 'deployment',
  /** statefulset */
  STATEFULSET = 'statefulset',
  /** daemonset */
  DAEMONSET = 'daemonset',
}

/**
 * Service configuration.
 *
 * @schema AgentPresetService
 */
export interface AgentPresetService {
  /**
   * The IP address of the service. Automatically assigned unless specified.
   *
   * @schema AgentPresetService#clusterIP
   */
  readonly clusterIp?: string;

  /**
   * A list of IP addresses assigned to this service, used for dual-stack services.
   *
   * @schema AgentPresetService#clusterIPs
   */
  readonly clusterIPs?: string[];

  /**
   * Determines how the service is exposed. Defaults to ClusterIP.
   *
   * @default ClusterIP.
   * @schema AgentPresetService#type
   */
  readonly type: AgentPresetServiceType;

  /**
   * A list of external IP addresses for the service to accept traffic on.
   *
   * @schema AgentPresetService#externalIPs
   */
  readonly externalIPs?: string[];

  /**
   * Specifies session affinity. Defaults to None.
   *
   * @default None.
   * @schema AgentPresetService#sessionAffinity
   */
  readonly sessionAffinity?: AgentPresetServiceSessionAffinity;

  /**
   * The load balancer IP address, if applicable and supported by the cloud provider.
   *
   * @schema AgentPresetService#loadBalancerIP
   */
  readonly loadBalancerIp?: string;

  /**
   * CIDR ranges that allow access to the load balancer.
   *
   * @schema AgentPresetService#loadBalancerSourceRanges
   */
  readonly loadBalancerSourceRanges?: string[];

  /**
   * The external reference name used by ExternalName services.
   *
   * @schema AgentPresetService#externalName
   */
  readonly externalName?: string;

  /**
   * Specifies how nodes handle external traffic. Defaults to Cluster.
   *
   * @default Cluster.
   * @schema AgentPresetService#externalTrafficPolicy
   */
  readonly externalTrafficPolicy?: AgentPresetServiceExternalTrafficPolicy;

  /**
   * The health check node port for LoadBalancer services with local traffic policy.
   *
   * @schema AgentPresetService#healthCheckNodePort
   */
  readonly healthCheckNodePort?: number;

  /**
   * If true, publishes addresses even if the pods are not ready.
   *
   * @schema AgentPresetService#publishNotReadyAddresses
   */
  readonly publishNotReadyAddresses?: boolean;

  /**
   * Configuration for session affinity.
   *
   * @schema AgentPresetService#sessionAffinityConfig
   */
  readonly sessionAffinityConfig?: any;

  /**
   * The IP families (IPv4, IPv6) assigned to the service for dual-stack clusters.
   *
   * @schema AgentPresetService#ipFamilies
   */
  readonly ipFamilies?: AgentPresetServiceIpFamilies[];

  /**
   * Defines the dual-stack behavior of the service.
   *
   * @schema AgentPresetService#ipFamilyPolicy
   */
  readonly ipFamilyPolicy?: AgentPresetServiceIpFamilyPolicy;

  /**
   * If true, allocates NodePorts for LoadBalancer services. Defaults to true.
   *
   * @default true.
   * @schema AgentPresetService#allocateLoadBalancerNodePorts
   */
  readonly allocateLoadBalancerNodePorts?: boolean;

  /**
   * The class of the load balancer implementation for this service.
   *
   * @schema AgentPresetService#loadBalancerClass
   */
  readonly loadBalancerClass?: string;

  /**
   * Describes how internal traffic is distributed. Defaults to Cluster.
   *
   * @default Cluster.
   * @schema AgentPresetService#internalTrafficPolicy
   */
  readonly internalTrafficPolicy?: AgentPresetServiceInternalTrafficPolicy;

  /**
   * Specifies traffic distribution preferences. This is an alpha feature.
   *
   * @schema AgentPresetService#trafficDistribution
   */
  readonly trafficDistribution?: string;
}

/**
 * Converts an object of type 'AgentPresetService' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetService(obj: AgentPresetService | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    clusterIP: obj.clusterIp,
    clusterIPs: obj.clusterIPs?.map((y) => y),
    type: obj.type,
    externalIPs: obj.externalIPs?.map((y) => y),
    sessionAffinity: obj.sessionAffinity,
    loadBalancerIP: obj.loadBalancerIp,
    loadBalancerSourceRanges: obj.loadBalancerSourceRanges?.map((y) => y),
    externalName: obj.externalName,
    externalTrafficPolicy: obj.externalTrafficPolicy,
    healthCheckNodePort: obj.healthCheckNodePort,
    publishNotReadyAddresses: obj.publishNotReadyAddresses,
    sessionAffinityConfig: obj.sessionAffinityConfig,
    ipFamilies: obj.ipFamilies?.map((y) => y),
    ipFamilyPolicy: obj.ipFamilyPolicy,
    allocateLoadBalancerNodePorts: obj.allocateLoadBalancerNodePorts,
    loadBalancerClass: obj.loadBalancerClass,
    internalTrafficPolicy: obj.internalTrafficPolicy,
    trafficDistribution: obj.trafficDistribution,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPresetPorts
 */
export interface AgentPresetPorts {
  /**
   * The name of the port.
   *
   * @schema AgentPresetPorts#name
   */
  readonly name?: string;

  /**
   * Specifies the port on the node that the container ports is exposed.
   *
   * @schema AgentPresetPorts#hostPort
   */
  readonly hostPort?: number;

  /**
   * The port number on which the service is exposed.
   *
   * @schema AgentPresetPorts#containerPort
   */
  readonly containerPort: number;

  /**
   * The protocol used by both the service and container ports. Defaults to TCP.
   *
   * @default TCP.
   * @schema AgentPresetPorts#protocol
   */
  readonly protocol?: string;

  /**
   * Specifies the host IP to bind the external port to.
   *
   * @schema AgentPresetPorts#hostIP
   */
  readonly hostIp?: string;

  /**
   * Specifies the port that the service should listen on.
   *
   * @schema AgentPresetPorts#servicePort
   */
  readonly servicePort?: number;

  /**
   * The port on each node to expose the service if the type is NodePort.
   *
   * @schema AgentPresetPorts#serviceNodePort
   */
  readonly serviceNodePort?: number;

  /**
   * The application protocol for this port, such as HTTP, HTTPS, or GRPC.
   *
   * @schema AgentPresetPorts#appProtocol
   */
  readonly appProtocol?: string;

  /**
   * The port on each node to expose the service if the type is NodePort.
   *
   * @schema AgentPresetPorts#nodePort
   */
  readonly nodePort?: number;
}

/**
 * Converts an object of type 'AgentPresetPorts' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetPorts(obj: AgentPresetPorts | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    name: obj.name,
    hostPort: obj.hostPort,
    containerPort: obj.containerPort,
    protocol: obj.protocol,
    hostIP: obj.hostIp,
    servicePort: obj.servicePort,
    serviceNodePort: obj.serviceNodePort,
    appProtocol: obj.appProtocol,
    nodePort: obj.nodePort,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPresetServiceAccount
 */
export interface AgentPresetServiceAccount {
  /**
   * Create the service account.
   *
   * @schema AgentPresetServiceAccount#create
   */
  readonly create: boolean;

  /**
   * Name of the service account to use if create is set to false.
   *
   * @schema AgentPresetServiceAccount#name
   */
  readonly name?: string;

  /**
   * Annotations for the service account if create is set to true.
   *
   * @schema AgentPresetServiceAccount#annotations
   */
  readonly annotations?: any;
}

/**
 * Converts an object of type 'AgentPresetServiceAccount' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetServiceAccount(
  obj: AgentPresetServiceAccount | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    create: obj.create,
    name: obj.name,
    annotations: obj.annotations,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPresetClusterRole
 */
export interface AgentPresetClusterRole {
  /**
   * Create the cluster role.
   *
   * @schema AgentPresetClusterRole#create
   */
  readonly create: boolean;

  /**
   * Name of the cluster role to use if create is set to false.
   *
   * @schema AgentPresetClusterRole#name
   */
  readonly name?: string;

  /**
   * Annotations for the cluster role if create is set to true.
   *
   * @schema AgentPresetClusterRole#annotations
   */
  readonly annotations?: any;

  /**
   * Rules for the cluster role to create if create is set to true.
   *
   * @schema AgentPresetClusterRole#rules
   */
  readonly rules?: any[];
}

/**
 * Converts an object of type 'AgentPresetClusterRole' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetClusterRole(
  obj: AgentPresetClusterRole | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    create: obj.create,
    name: obj.name,
    annotations: obj.annotations,
    rules: obj.rules?.map((y) => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPriorityClass
 */
export interface AgentPriorityClass {
  /**
   * Create the priority class.
   *
   * @schema AgentPriorityClass#create
   */
  readonly create: boolean;

  /**
   * Name of the priority class to use if create is set to false.
   *
   * @schema AgentPriorityClass#name
   */
  readonly name?: string;

  /**
   * Value of the priority class.
   *
   * @schema AgentPriorityClass#value
   */
  readonly value?: number;

  /**
   * Preemption policy for the priority class.
   *
   * @schema AgentPriorityClass#preemptionPolicy
   */
  readonly preemptionPolicy?: AgentPriorityClassPreemptionPolicy;

  /**
   * Set the priority class as the global default.
   *
   * @schema AgentPriorityClass#globalDefault
   */
  readonly globalDefault?: boolean;

  /**
   * Description of the priority class.
   *
   * @schema AgentPriorityClass#description
   */
  readonly description?: string;
}

/**
 * Converts an object of type 'AgentPriorityClass' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPriorityClass(obj: AgentPriorityClass | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    create: obj.create,
    name: obj.name,
    value: obj.value,
    preemptionPolicy: obj.preemptionPolicy,
    globalDefault: obj.globalDefault,
    description: obj.description,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Volume type used for Agent state persistence.
 *
 * @schema AgentPresetStatePersistence
 */
export enum AgentPresetStatePersistence {
  /** HostPath */
  HOST_PATH = 'HostPath',
  /** EmptyDir */
  EMPTY_DIR = 'EmptyDir',
  /** None */
  NONE = 'None',
}

/**
 * @schema AgentPresetAgent
 */
export interface AgentPresetAgent {
  /**
   * @schema AgentPresetAgent#monitoring
   */
  readonly monitoring?: AgentPresetAgentMonitoring;
}

/**
 * Converts an object of type 'AgentPresetAgent' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetAgent(obj: AgentPresetAgent | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    monitoring: toJson_AgentPresetAgentMonitoring(obj.monitoring),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Providers configuration for the deployment.
 *
 * @schema AgentPresetProviders
 */
export interface AgentPresetProviders {
  /**
   * @schema AgentPresetProviders#kubernetes_leaderelection
   */
  readonly kubernetesLeaderelection?: AgentPresetProvidersKubernetesLeaderelection;

  /**
   * @schema AgentPresetProviders#kubernetes
   */
  readonly kubernetes?: AgentPresetProvidersKubernetes;
}

/**
 * Converts an object of type 'AgentPresetProviders' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetProviders(obj: AgentPresetProviders | undefined): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    kubernetes_leaderelection: toJson_AgentPresetProvidersKubernetesLeaderelection(obj.kubernetesLeaderelection),
    kubernetes: toJson_AgentPresetProvidersKubernetes(obj.kubernetes),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema ValueFromValueFromSecret
 */
export interface ValueFromValueFromSecret {
  /**
   * @schema ValueFromValueFromSecret#name
   */
  readonly name: string;

  /**
   * @schema ValueFromValueFromSecret#key
   */
  readonly key: string;
}

/**
 * Converts an object of type 'ValueFromValueFromSecret' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ValueFromValueFromSecret(
  obj: ValueFromValueFromSecret | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    name: obj.name,
    key: obj.key,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema OutputObjectQueueMemFlush
 */
export interface OutputObjectQueueMemFlush {
  /**
   * The maximum wait time for queue.mem.flush.min_events to be fulfilled. If set to 0s, events are available to the output immediately. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObjectQueueMemFlush#timeout
   */
  readonly timeout?: string;

  /**
   * flush.min_events is a legacy parameter, and new configurations should prefer to control batch size with bulk_max_size. As of 8.13, there is never a performance advantage to limiting batch size with flush.min_events instead of bulk_max_size. If using Elasticsearch the Custom preset must be set to use this
   *
   * @schema OutputObjectQueueMemFlush#min_events
   */
  readonly minEvents?: number;
}

/**
 * Converts an object of type 'OutputObjectQueueMemFlush' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_OutputObjectQueueMemFlush(
  obj: OutputObjectQueueMemFlush | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    timeout: obj.timeout,
    min_events: obj.minEvents,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Stream variables.
 *
 * @schema ElasticAgentKubernetesContainersLogsVars
 */
export interface ElasticAgentKubernetesContainersLogsVars {
  /**
   * Enable container logs stream default processors.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#enabledDefaultProcessors
   */
  readonly enabledDefaultProcessors?: boolean;

  /**
   * Use Symlinks.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#symlinks
   */
  readonly symlinks?: boolean;

  /**
   * Additional parsers configuration.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#additionalParsersConfig
   */
  readonly additionalParsersConfig?: any[];

  /**
   * Container parser's stream configuration.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#containerParserStream
   */
  readonly containerParserStream?: string;

  /**
   * Container parser's format configuration.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#containerParserFormat
   */
  readonly containerParserFormat?: string;

  /**
   * Additional processors to use on the container logs streams. Processors are used to reduce the number of fields in the exported event or to enhance the event with metadata. This executes in the agent before the events are shipped.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#processors
   */
  readonly processors?: any[];

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema ElasticAgentKubernetesContainersLogsVars#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'ElasticAgentKubernetesContainersLogsVars' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_ElasticAgentKubernetesContainersLogsVars(
  obj: ElasticAgentKubernetesContainersLogsVars | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabledDefaultProcessors: obj.enabledDefaultProcessors,
    symlinks: obj.symlinks,
    additionalParsersConfig: obj.additionalParsersConfig?.map((y) => y),
    containerParserStream: obj.containerParserStream,
    containerParserFormat: obj.containerParserFormat,
    processors: obj.processors?.map((y) => y),
    additionalValues:
      obj.additionalValues === undefined
        ? undefined
        : Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {}),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Determines how the service is exposed. Defaults to ClusterIP.
 *
 * @default ClusterIP.
 * @schema AgentPresetServiceType
 */
export enum AgentPresetServiceType {
  /** ClusterIP */
  CLUSTER_IP = 'ClusterIP',
  /** NodePort */
  NODE_PORT = 'NodePort',
  /** LoadBalancer */
  LOAD_BALANCER = 'LoadBalancer',
}

/**
 * Specifies session affinity. Defaults to None.
 *
 * @default None.
 * @schema AgentPresetServiceSessionAffinity
 */
export enum AgentPresetServiceSessionAffinity {
  /** None */
  NONE = 'None',
  /** ClientIP */
  CLIENT_IP = 'ClientIP',
}

/**
 * Specifies how nodes handle external traffic. Defaults to Cluster.
 *
 * @default Cluster.
 * @schema AgentPresetServiceExternalTrafficPolicy
 */
export enum AgentPresetServiceExternalTrafficPolicy {
  /** Cluster */
  CLUSTER = 'Cluster',
  /** Local */
  LOCAL = 'Local',
}

/**
 * @schema AgentPresetServiceIpFamilies
 */
export enum AgentPresetServiceIpFamilies {
  /** IPv4 */
  I_PV4 = 'IPv4',
  /** IPv6 */
  I_PV6 = 'IPv6',
}

/**
 * Defines the dual-stack behavior of the service.
 *
 * @schema AgentPresetServiceIpFamilyPolicy
 */
export enum AgentPresetServiceIpFamilyPolicy {
  /** SingleStack */
  SINGLE_STACK = 'SingleStack',
  /** PreferDualStack */
  PREFER_DUAL_STACK = 'PreferDualStack',
  /** RequireDualStack */
  REQUIRE_DUAL_STACK = 'RequireDualStack',
}

/**
 * Describes how internal traffic is distributed. Defaults to Cluster.
 *
 * @default Cluster.
 * @schema AgentPresetServiceInternalTrafficPolicy
 */
export enum AgentPresetServiceInternalTrafficPolicy {
  /** Cluster */
  CLUSTER = 'Cluster',
  /** Local */
  LOCAL = 'Local',
}

/**
 * Preemption policy for the priority class.
 *
 * @schema AgentPriorityClassPreemptionPolicy
 */
export enum AgentPriorityClassPreemptionPolicy {
  /** Never */
  NEVER = 'Never',
  /** PreemptLowerPriority */
  PREEMPT_LOWER_PRIORITY = 'PreemptLowerPriority',
}

/**
 * @schema AgentPresetAgentMonitoring
 */
export interface AgentPresetAgentMonitoring {
  /**
   * @schema AgentPresetAgentMonitoring#namespace
   */
  readonly namespace: string;

  /**
   * @schema AgentPresetAgentMonitoring#use_output
   */
  readonly useOutput: string;

  /**
   * @schema AgentPresetAgentMonitoring#enabled
   */
  readonly enabled: boolean;

  /**
   * @schema AgentPresetAgentMonitoring#logs
   */
  readonly logs: boolean;

  /**
   * @schema AgentPresetAgentMonitoring#metrics
   */
  readonly metrics: boolean;
}

/**
 * Converts an object of type 'AgentPresetAgentMonitoring' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetAgentMonitoring(
  obj: AgentPresetAgentMonitoring | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    namespace: obj.namespace,
    use_output: obj.useOutput,
    enabled: obj.enabled,
    logs: obj.logs,
    metrics: obj.metrics,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPresetProvidersKubernetesLeaderelection
 */
export interface AgentPresetProvidersKubernetesLeaderelection {
  /**
   * @schema AgentPresetProvidersKubernetesLeaderelection#enabled
   */
  readonly enabled?: boolean;
}

/**
 * Converts an object of type 'AgentPresetProvidersKubernetesLeaderelection' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetProvidersKubernetesLeaderelection(
  obj: AgentPresetProvidersKubernetesLeaderelection | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema AgentPresetProvidersKubernetes
 */
export interface AgentPresetProvidersKubernetes {
  /**
   * @schema AgentPresetProvidersKubernetes#enabled
   */
  readonly enabled?: boolean;

  /**
   * @schema AgentPresetProvidersKubernetes#node
   */
  readonly node?: string;

  /**
   * @schema AgentPresetProvidersKubernetes#scope
   */
  readonly scope?: string;
}

/**
 * Converts an object of type 'AgentPresetProvidersKubernetes' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_AgentPresetProvidersKubernetes(
  obj: AgentPresetProvidersKubernetes | undefined,
): Record<string, any> | undefined {
  if (obj === undefined) {
    return undefined;
  }
  const result = {
    enabled: obj.enabled,
    node: obj.node,
    scope: obj.scope,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined ? r : { ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
