# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.10/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hillshade-combinations
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 100
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: 'new-zealand'
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: 'new-zealand'
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v8" or "latest"'
        value: 'v8'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: source_geospatial_categories
        description: 'Geospatial categories of the source elevation data as stringified json, e.g. ["dem"] or ["dem", "dsm"]'
        value: '["dem", "dsm"]'
      - name: gsd
        description: 'Dataset GSD in metres, e.g., "1" for 1 metre'
        default: '1'
      - name: hillshade_presets
        description: 'Hillshade presets to use, as stringified json, e.g. ["hillshade"] or ["hillshade-igor", "hillshade"]'
        value: '["hillshade-igor", "hillshade"]'
      - name: domain
        description: 'Data domain of the dataset, e.g. "land", "coastal"'
        value: 'land'
        enum:
          - 'land'
          - 'coastal'
      - name: bucket_name
        description: 'Name of the bucket to use, e.g. "nz-elevation" or "nz-coastal"'
        value: 'nz-elevation'
        enum:
          - 'nz-elevation'
          - 'nz-coastal'
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '4'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      steps:
        - - name: elevation-type
            template: each-elevation-type
            arguments:
              parameters:
                - name: source_geospatial_category
                  value: '{{item}}'
            withParam: '{{workflow.parameters.source_geospatial_categories}}'

    - name: each-elevation-type
      inputs:
        parameters:
          - name: source_geospatial_category
      steps:
        - - name: hillshade-presets
            templateRef:
              name: hillshade
              template: main
            arguments:
              parameters:
                - name: version_argo_tasks
                  value: '{{workflow.parameters.version_argo_tasks}}'
                - name: version_basemaps_cli
                  value: '{{workflow.parameters.version_basemaps_cli}}'
                - name: version_topo_imagery
                  value: '{{workflow.parameters.version_topo_imagery}}'
                - name: ticket
                  value: '{{workflow.parameters.ticket}}'
                - name: source
                  value: 's3://{{workflow.parameters.bucket_name}}/new-zealand/new-zealand/{{inputs.parameters.source_geospatial_category}}_{{workflow.parameters.gsd}}m/2193/'
                - name: domain
                  value: '{{workflow.parameters.domain}}'
                - name: source_geospatial_category
                  value: '{{inputs.parameters.source_geospatial_category}}'
                - name: gsd
                  value: '{{workflow.parameters.gsd}}'
                - name: odr_url
                  value: 's3://{{workflow.parameters.bucket_name}}/new-zealand/new-zealand/{{inputs.parameters.source_geospatial_category}}-{{item}}_{{workflow.parameters.gsd}}m/2193/'
                - name: hillshade_preset
                  value: '{{item}}'
                - name: publish_to_odr
                  value: '{{workflow.parameters.publish_to_odr}}'
                - name: copy_option
                  value: '{{workflow.parameters.copy_option}}'
            withParam: '{{workflow.parameters.hillshade_presets}}'

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-log-notification` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-log-notification
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
