# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hillshade
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: 'new-zealand'
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: 'new-zealand'
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v7.1" or "latest"'
        value: 'v7'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: source
        description: 'Location of the input elevation data to create hillshade.'
        value: 's3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/'
      - name: source_geospatial_category
        description: 'Geospatial category of the source elevation data, e.g. "dem" or "dsm"'
        value: 'dem'
        enum:
          - 'dem'
          - 'dsm'
      - name: gsd
        description: 'Dataset GSD in metres, e.g., "1" for 1 metre'
        default: '1'
      - name: odr_url
        description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/"'
        value: ''
      - name: hillshade_preset
        description: 'Hillshade preset to use, must be one of "hillshade" or "hillshade-igor"'
        value: 'hillshade'
        enum:
          - 'hillshade-igor'
          - 'hillshade'
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '4'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      inputs:
        parameters:
          - name: source_geospatial_category
            description: 'Geospatial category of the source elevation data, e.g. "dem" or "dsm"'
            value: '{{workflow.parameters.source_geospatial_category}}'
          - name: hillshade_preset
            description: 'Hillshade preset to use, must be one of "hillshade" or "hillshade-igor"'
            value: '{{workflow.parameters.hillshade_preset}}'
          - name: source
            description: 'Location of the input elevation data to create hillshade.'
            value: '{{workflow.parameters.source}}'
          - name: odr_url
            description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/"'
            value: '{{workflow.parameters.odr_url}}'
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: get-location
            templateRef:
              name: tpl-get-location
              template: main
            arguments:
              parameters:
                - name: version_argo_tasks
                  value: '{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'

          - name: stac-setup-hillshade
            templateRef:
              name: tpl-at-stac-setup
              template: main
            arguments:
              parameters:
                - name: gsd
                  value: '{{=sprig.trim(workflow.parameters.gsd)}}'
                - name: region
                  value: 'new-zealand'
                - name: geospatial_category
                  value: '{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}'
                - name: odr_url
                  value: '{{inputs.parameters.odr_url}}'
                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks}}'

          - name: identify-updated-items
            templateRef:
              name: tpl-at-identify-updated-items
              template: main
            arguments:
              parameters:
                - name: targetCollection
                  value: '{{= inputs.parameters.odr_url == "" ? "" : sprig.trimSuffix("/", inputs.parameters.odr_url) + "/collection.json" }}'
                - name: sourceCollections
                  value: '{{=sprig.trimSuffix("/", inputs.parameters.source)}}/collection.json'
                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks}}'

          - name: group
            when: '{{= len(sprig.fromJson(tasks["identify-updated-items"].outputs.parameters["file-list-content"])) > 0 }}'
            templateRef:
              name: tpl-at-group
              template: main
            arguments:
              artifacts:
                - name: input
                  from: '{{ tasks.identify-updated-items.outputs.artifacts.files }}'
              parameters:
                - name: size
                  value: '{{=sprig.trim(workflow.parameters.group)}}'
                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks}}'
            depends: 'identify-updated-items.Succeeded && stac-setup-hillshade.Succeeded && get-location.Succeeded'

          - name: generate-hillshade
            templateRef:
              name: tpl-ti-generate-hillshade
              template: main
            arguments:
              parameters:
                - name: group_id
                  value: '{{item}}'
                - name: hillshade_preset
                  value: '{{inputs.parameters.hillshade_preset}}'
                - name: version_topo_imagery
                  value: '{{= workflow.parameters.version_topo_imagery}}'
                - name: target # not using flat/ here, but {{workflow.parameters.hillshade_preset}}/ to keep temporary HS output separate
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
                - name: collection_id
                  value: '{{tasks.stac-setup-hillshade.outputs.parameters.collection_id}}'
                - name: gsd
                  value: '{{=sprig.trim(workflow.parameters.gsd)}}'
                - name: current_datetime
                  value: '{{tasks.stac-setup-hillshade.finishedAt}}'
                - name: odr_url
                  value: '{{inputs.parameters.odr_url}}'
              artifacts:
                - name: group_data
                  from: '{{tasks.group.outputs.artifacts.output}}'
            depends: 'get-location.Succeeded && stac-setup-hillshade.Succeeded && group.Succeeded'
            withParam: '{{tasks.group.outputs.parameters.output}}'

          - name: create-collection
            templateRef:
              name: tpl-ti-create-collection
              template: main
            arguments:
              parameters:
                - name: collection_id
                  value: '{{tasks.stac-setup-hillshade.outputs.parameters.collection_id}}'
                - name: linz_slug
                  value: '{{tasks.stac-setup-hillshade.outputs.parameters.linz_slug}}'
                - name: location
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
                - name: current_datetime
                  value: '{{tasks.stac-setup-hillshade.finishedAt}}' # not stac-setup
                - name: odr_url
                  value: '{{inputs.parameters.odr_url}}'
                - name: category
                  value: '{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}'
                - name: region
                  value: 'new-zealand'
                - name: gsd
                  value: '{{=sprig.trim(workflow.parameters.gsd)}}'
                - name: lifecycle
                  value: 'ongoing'
                - name: producer
                  value: 'Toitū Te Whenua Land Information New Zealand'
                - name: licensor
                  value: 'Toitū Te Whenua Land Information New Zealand'
                - name: create_capture_dates
                  value: 'false'
                - name: keep_title
                  value: 'true'
                - name: version_topo_imagery
                  value: '{{= workflow.parameters.version_topo_imagery}}'
            depends: 'generate-hillshade.Succeeded'

          - name: stac-validate-all
            templateRef:
              name: tpl-at-stac-validate
              template: main
            arguments:
              parameters:
                - name: uri
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/collection.json'
              artifacts:
                - name: stac-result
                  raw:
                    data: '{{tasks.stac-validate-all.outputs.result}}'
            depends: 'create-collection.Succeeded'
            when: "'{{inputs.parameters.odr_url}}' == ''"

          - name: stac-validate-only-updated
            templateRef:
              name: stac-validate-parallel # Needs to validate a list of STAC documents
              template: main
            arguments:
              parameters:
                - name: uri
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
                - name: recursive
                  value: 'false' # The Collection might have some Items that are only in the published location
                - name: checksum_links
                  value: 'false'
                - name: checksum_assets
                  value: 'true'
                - name: include
                  value: '\.json$' # FIXME: For now, assuming we have only STAC as JSON files in the scratch location
                - name: concurrency
                  value: '50'
            depends: 'create-collection.Succeeded'
            when: "'{{inputs.parameters.odr_url}}' != ''"

          - name: create-config
            arguments:
              parameters:
                - name: location
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
                - name: bucket
                  value: '{{tasks.get-location.outputs.parameters.bucket}}'
                - name: key
                  value: '{{tasks.get-location.outputs.parameters.key}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
            template: create-config
            depends: 'generate-hillshade.Succeeded'

          - name: publish-odr
            templateRef:
              name: publish-odr
              template: main
            when: "'{{workflow.parameters.publish_to_odr}}' == 'true'"
            arguments:
              parameters:
                - name: source
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.source_geospatial_category}}-{{inputs.parameters.hillshade_preset}}/flat/'
                - name: target_bucket_name
                  value: 'nz-elevation'
                - name: copy_option
                  value: '{{=sprig.trim(workflow.parameters.copy_option)}}'
                - name: ticket
                  value: '{{=sprig.trim(workflow.parameters.ticket)}}'
                - name: odr_url
                  value: '{{inputs.parameters.odr_url}}'
            depends: '(stac-validate-all.Succeeded || stac-validate-only-updated.Succeeded) && create-config.Succeeded'

      outputs:
        parameters:
          - name: target
            valueFrom:
              parameter: '{{tasks["get-location"].outputs.parameters.location}}'
              default: ''

    - name: create-config
      inputs:
        parameters:
          - name: location
            description: 'Location of the imagery to create config for'
          - name: bucket
          - name: key
      container:
        image: 'ghcr.io/linz/basemaps/cli:{{=sprig.trim(workflow.parameters.version_basemaps_cli)}}'
        command: [node, /app/node_modules/@basemaps/cogify/dist/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - 'config'
          - '{{=sprig.trimSuffix("/", inputs.parameters.location)}}'
      outputs:
        parameters:
          - name: url
            description: 'Basemaps URL to view the imagery'
            valueFrom:
              path: '/tmp/cogify/config-url'
          - name: config
            description: 'Location of the config file'
            valueFrom:
              path: '/tmp/cogify/config-path'
        artifacts:
          - name: url
            path: '/tmp/cogify/config-url'
            s3:
              bucket: '{{=sprig.trim(inputs.parameters.bucket)}}'
              key: '{{=sprig.trimSuffix("/", inputs.parameters.key)}}/config-url'
            archive:
              none: {}

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-exit-handler` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-exit-handler
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
