# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: merge-layers
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: workflow.parameters.region
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: workflow.parameters.region
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v7.1" or "latest"'
        value: 'v7'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: top_layer_source
        description: 'Location of the top layer (e.g. 1m DEM hillshade). Semi-colon separated list of paths.'
        value: 's3://nz-elevation/new-zealand/new-zealand/dem-hillshade-igor_1m/2193/'
      - name: base_layer_source
        description: 'Location of the base layers (e.g. 8m DEM hillshade) to fill any gaps in the top layer. Semi-colon separated list of paths.'
        value: 's3://nz-elevation/new-zealand/new-zealand-contour/dem-hillshade-igor_8m/2193/'
      - name: odr_url
        description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade-igor/2193/"'
        value: 's3://nz-elevation/new-zealand/new-zealand/dem-hillshade-igor/2193/'
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '4'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
      - name: geospatial_category
        description: 'Geospatial category of the dataset, e.g. "dem-hillshade"'
        value: 'dem-hillshade-igor'
        enum:
          - 'aerial-photos'
          - 'urban-aerial-photos'
          - 'rural-aerial-photos'
          - 'scanned-aerial-photos'
          - 'dem'
          - 'dsm'
          - 'satellite-imagery'
          - 'dem-hillshade'
          - 'dem-hillshade-igor'
          - 'dsm-hillshade'
          - 'dsm-hillshade-igor'
      - name: create_capture_area
        value: 'true'
        enum:
          - 'false'
          - 'true'
      - name: create_capture_dates
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: gsd
        value: '1'
      - name: scale_to_resolution
        description: 'Scale output TIFFs to x,y resolution (e.g. 1,1 - leave blank for no scaling)'
        value: '1,1'
      - name: source_epsg
        value: '2193'
      - name: target_epsg
        value: '2193'
      - name: include
        description: 'Regular expression pattern match for paths/files to include e.g ".tiff?$"'
        value: '.tiff?$'
      - name: scale
        description: 'Scale of the standardised output imagery'
        value: '50000'
        enum:
          - '500'
          - '1000'
          - '2000'
          - '5000'
          - '10000'
          - '50000'
          - 'None'
      - name: target_bucket_name
        description: 'The ODR bucket name to publish to'
        value: 'nz-elevation'
        enum:
          - 'nz-imagery'
          - 'nz-elevation'
      - name: region
        value: 'new-zealand'
      - name: gdal_compression_preset
        value: 'dem_lerc'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      inputs:
        parameters:
          - name: version_argo_tasks
            default: '{{workflow.parameters.version_argo_tasks}}'
          - name: version_basemaps_cli
            default: '{{workflow.parameters.version_basemaps_cli}}'
          - name: version_topo_imagery
            default: '{{workflow.parameters.version_topo_imagery}}'
          - name: ticket
            default: '{{workflow.parameters.ticket}}'
          - name: top_layer_source
            default: '{{workflow.parameters.top_layer_source}}'
          - name: base_layer_source
            default: '{{workflow.parameters.base_layer_source}}'
          - name: odr_url
            default: '{{workflow.parameters.odr_url}}'
          - name: group
            default: '{{workflow.parameters.group}}'
          - name: publish_to_odr
            default: '{{workflow.parameters.publish_to_odr}}'
          - name: copy_option
            default: '{{workflow.parameters.copy_option}}'
          - name: geospatial_category
            default: '{{workflow.parameters.geospatial_category}}'
          - name: create_capture_area
            default: '{{workflow.parameters.create_capture_area}}'
          - name: create_capture_dates
            default: '{{workflow.parameters.create_capture_dates}}'
          - name: gsd
            default: '{{workflow.parameters.gsd}}'
          - name: scale_to_resolution
            default: '{{workflow.parameters.scale_to_resolution}}'
          - name: source_epsg
            default: '{{workflow.parameters.source_epsg}}'
          - name: target_epsg
            default: '{{workflow.parameters.target_epsg}}'
          - name: include
            default: '{{workflow.parameters.include}}'
          - name: scale
            default: '{{workflow.parameters.scale}}'
          - name: target_bucket_name
            default: '{{workflow.parameters.target_bucket_name}}'
          - name: region
            default: '{{workflow.parameters.region}}'
          - name: gdal_compression_preset
            default: '{{workflow.parameters.gdal_compression_preset}}'
      dag:
        tasks:
          - name: get-location
            templateRef:
              name: tpl-get-location
              template: main

          - name: stac-setup
            templateRef:
              name: tpl-at-stac-setup
              template: main
            arguments:
              parameters:
                - name: gsd
                  value: '{{=sprig.trim(inputs.parameters.gsd)}}'
                - name: region
                  value: '{{=sprig.trim(inputs.parameters.region)}}'
                - name: geospatial_category
                  value: '{{inputs.parameters.geospatial_category}}'
                - name: odr_url
                  value: '{{=sprig.trim(inputs.parameters.odr_url)}}'
                - name: version
                  value: '{{=sprig.trim(inputs.parameters.version_argo_tasks)}}'

          - name: identify-updated-items
            templateRef:
              name: tpl-at-identify-updated-items
              template: main
            arguments:
              parameters:
                - name: targetCollection
                  value: '{{= inputs.parameters.odr_url == "" ? "" : sprig.trimSuffix("/", inputs.parameters.odr_url) + "/collection.json" }}'
                - name: sourceCollections
                  value: '{{= inputs.parameters.base_layer_source == "" ? "" : sprig.trimSuffix("/", inputs.parameters.base_layer_source) + "/collection.json;" }}{{=sprig.trimSuffix("/", inputs.parameters.top_layer_source)}}/collection.json'
                - name: version
                  value: '{{= inputs.parameters.version_argo_tasks}}'

          - name: group
            when: "'{{tasks.identify-updated-items.outputs.parameters.file-list-content}}' == '[]'"
            templateRef:
              name: tpl-at-group
              template: main
            arguments:
              artifacts:
                - name: input
                  from: '{{ tasks.identify-updated-items.outputs.artifacts.files }}'
              parameters:
                - name: size
                  value: '{{inputs.parameters.group}}'
                - name: version
                  value: '{{= inputs.parameters.version_argo_tasks}}'
            depends: 'identify-updated-items.Succeeded'

          - name: standardise-validate
            templateRef:
              name: tpl-ti-standardise-validate
              template: main
            arguments:
              parameters:
                - name: group_id
                  value: '{{item}}'
                - name: collection_id
                  value: '{{tasks.stac-setup.outputs.parameters.collection_id}}'
                - name: current_datetime
                  value: '{{tasks.stac-setup.finishedAt}}'
                - name: target
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/flat/'
                - name: compression
                  value: '{{inputs.parameters.gdal_compression_preset}}'
                - name: odr_url
                  value: '{{=sprig.trim(inputs.parameters.odr_url)}}'
                - name: scale_to_resolution
                  value: '{{=sprig.trim(inputs.parameters.scale_to_resolution)}}'
                - name: source_epsg
                  value: '{{=sprig.trim(inputs.parameters.source_epsg)}}'
                - name: target_epsg
                  value: '{{=sprig.trim(inputs.parameters.target_epsg)}}'
                - name: version_topo_imagery
                  value: '{{= inputs.parameters.version_topo_imagery}}'
                - name: create_capture_area
                  value: '{{inputs.parameters.create_capture_area}}'
                - name: create_capture_dates
                  value: '{{inputs.parameters.create_capture_dates}}'
                - name: gsd
                  value: '{{=sprig.trim(inputs.parameters.gsd)}}'
              artifacts:
                - name: group_data
                  from: '{{ tasks.group.outputs.artifacts.output }}'
            depends: 'group.Succeeded && get-location.Succeeded && stac-setup.Succeeded'
            withParam: '{{ tasks.group.outputs.parameters.output }}'

          - name: create-collection
            templateRef:
              name: tpl-ti-create-collection
              template: main
            arguments:
              parameters:
                - name: collection_id
                  value: '{{tasks.stac-setup.outputs.parameters.collection_id}}'
                - name: linz_slug
                  value: '{{tasks.stac-setup.outputs.parameters.linz_slug}}'
                - name: location
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/flat/'
                - name: current_datetime
                  value: '{{tasks.stac-setup.finishedAt}}'
                - name: category
                  value: '{{inputs.parameters.geospatial_category}}'
                - name: region
                  value: '{{=sprig.trim(inputs.parameters.region)}}'
                - name: gsd
                  value: '{{=sprig.trim(inputs.parameters.gsd)}}'
                - name: lifecycle
                  value: 'ongoing'
                - name: producer
                  value: 'Toitū Te Whenua Land Information New Zealand'
                - name: licensor
                  value: 'Toitū Te Whenua Land Information New Zealand'
                - name: create_capture_area
                  value: '{{inputs.parameters.create_capture_area}}'
                - name: create_capture_dates
                  value: '{{inputs.parameters.create_capture_dates}}'
                - name: version_topo_imagery
                  value: '{{= inputs.parameters.version_topo_imagery}}'
            depends: 'standardise-validate.Succeeded'

          - name: stac-validate
            templateRef:
              name: tpl-at-stac-validate
              template: main
            arguments:
              parameters:
                - name: uri
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/flat/collection.json'
              artifacts:
                - name: stac-result
                  raw:
                    data: '{{tasks.stac-validate.outputs.result}}'
            depends: 'create-collection'

          - name: create-config
            when: "'{{inputs.parameters.target_epsg}}' =~ '2193|3857'"
            arguments:
              parameters:
                - name: location
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/'
                - name: bucket
                  value: '{{tasks.get-location.outputs.parameters.bucket}}'
                - name: key
                  value: '{{tasks.get-location.outputs.parameters.key}}/{{inputs.parameters.geospatial_category}}'
            template: create-config
            depends: 'standardise-validate'

          - name: publish-odr
            templateRef:
              name: publish-odr
              template: main
            when: "'{{inputs.parameters.publish_to_odr}}' == 'true'"
            arguments:
              parameters:
                - name: source
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/flat/'
                - name: target_bucket_name
                  value: '{{inputs.parameters.target_bucket_name}}'
                - name: copy_option
                  value: '{{inputs.parameters.copy_option}}'
                - name: ticket
                  value: '{{=sprig.trim(inputs.parameters.ticket)}}'
                - name: odr_url
                  value: '{{=sprig.trim(inputs.parameters.odr_url)}}'
            depends: 'stac-validate.Succeeded && create-config.Succeeded'

      outputs:
        parameters:
          - name: target
            valueFrom:
              parameter: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/{{inputs.parameters.geospatial_category}}/'
              default: ''

    - name: create-config
      inputs:
        parameters:
          - name: location
            description: 'Location of the imagery to create config for'
          - name: bucket
          - name: key
      container:
        image: 'ghcr.io/linz/basemaps/cli:{{=sprig.trim(workflow.parameters.version_basemaps_cli)}}'
        command: [node, /app/node_modules/@basemaps/cogify/dist/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - 'config'
          - '{{=sprig.trimSuffix("/", inputs.parameters.location)}}/flat/'
      outputs:
        parameters:
          - name: url
            description: 'Basemaps URL to view the imagery'
            valueFrom:
              path: '/tmp/cogify/config-url'
          - name: config
            description: 'Location of the config file'
            valueFrom:
              path: '/tmp/cogify/config-path'
        artifacts:
          - name: url
            path: '/tmp/cogify/config-url'
            s3:
              bucket: '{{inputs.parameters.bucket}}'
              key: '{{=sprig.trimSuffix("/", inputs.parameters.key)}}/flat/config-url'
            archive:
              none: {}

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-exit-handler` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-exit-handler
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
