# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: merge-national-hillshades
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: 'new-zealand'
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: 'new-zealand'
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v7.1" or "latest"'
        value: 'v7'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: hillshades
        description: 'Specify the top_layer, base_layer, and odr_url for each hillshade preset.'
        value: '[
          {
          "preset": "hillshade",
          "top_layer": "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade_1m/2193/",
          "base_layer": "s3://nz-elevation/new-zealand/new-zealand-contour/dem-hillshade_8m/2193/",
          "odr_url": "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade/2193/"
          }, {
          "preset": "hillshade-igor",
          "top_layer": "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade-igor_1m/2193/",
          "base_layer": "s3://nz-elevation/new-zealand/new-zealand-contour/dem-hillshade-igor_8m/2193/",
          "odr_url": "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade-igor/2193/"
          }
          ]'
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '4'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
      - name: geospatial_category
        description: 'Geospatial category of the source dataset, e.g. "dem" (will append hillshade preset)'
        value: 'dem'
        enum:
          - 'aerial-photos'
          - 'urban-aerial-photos'
          - 'rural-aerial-photos'
          - 'scanned-aerial-photos'
          - 'dem'
          - 'dsm'
          - 'satellite-imagery'
          - 'dem-hillshade'
          - 'dem-hillshade-igor'
      - name: create_capture_area
        value: 'true'
        enum:
          - 'false'
          - 'true'
      - name: create_capture_dates
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: gsd
        value: '1'
      - name: scale_to_resolution
        description: 'Scale output TIFFs to x,y resolution (e.g. 1,1 - leave blank for no scaling)'
        value: '1,1'
      - name: source_epsg
        value: '2193'
      - name: target_epsg
        value: '2193'
      - name: include
        description: 'Regular expression pattern match for paths/files to include e.g ".tiff?$"'
        value: '.tiff?$'
      - name: scale
        description: 'Scale of the standardised output imagery'
        value: '50000'
        enum:
          - '500'
          - '1000'
          - '2000'
          - '5000'
          - '10000'
          - '50000'
          - 'None'
      - name: target_bucket_name
        description: 'The ODR bucket name to publish to'
        value: 'nz-elevation'
        enum:
          - 'nz-imagery'
          - 'nz-elevation'
      - name: region
        value: 'new-zealand'
      - name: gdal_compression_preset
        value: 'dem_lerc'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: national-hillshade-merge
            templateRef:
              name: tpl-merge-hillshade-layers
              template: main
            arguments:
              parameters:
                - name: version_argo_tasks
                  value: '{{workflow.parameters.version_argo_tasks}}'
                - name: version_basemaps_cli
                  value: '{{workflow.parameters.version_basemaps_cli}}'
                - name: version_topo_imagery
                  value: '{{workflow.parameters.version_topo_imagery}}'
                - name: ticket
                  value: '{{workflow.parameters.ticket}}'
                - name: top_layer_source
                  value: '{{item.top_layer}}'
                - name: base_layer_source
                  value: '{{item.base_layer}}'
                - name: odr_url
                  value: '{{item.odr_url}}'
                - name: group
                  value: '{{workflow.parameters.group}}'
                - name: publish_to_odr
                  value: '{{workflow.parameters.publish_to_odr}}'
                - name: copy_option
                  value: '{{workflow.parameters.copy_option}}'
                - name: create_capture_area
                  value: '{{workflow.parameters.create_capture_area}}'
                - name: gsd
                  value: '{{workflow.parameters.gsd}}'
                - name: scale_to_resolution
                  value: '{{workflow.parameters.scale_to_resolution}}'
                - name: source_epsg
                  value: '{{workflow.parameters.source_epsg}}'
                - name: target_epsg
                  value: '{{workflow.parameters.target_epsg}}'
                - name: include
                  value: '{{workflow.parameters.include}}'
                - name: scale
                  value: '{{workflow.parameters.scale}}'
                - name: target_bucket_name
                  value: '{{workflow.parameters.target_bucket_name}}'
                - name: region
                  value: '{{workflow.parameters.region}}'
                - name: geospatial_category
                  value: '{{workflow.parameters.geospatial_category}}-{{item.preset}}'
                - name: gdal_compression_preset
                  value: '{{workflow.parameters.gdal_compression_preset}}'
            withParam: '{{workflow.parameters.hillshades}}'

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-exit-handler` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-exit-handler
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
