# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: national-dem
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: 'new-zealand'
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: 'new-zealand'
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v7.1" or "latest"'
        value: 'v7'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: config_file
        description: 'Location of the configuration file listing the source datasets to merge.'
        value: 'https://raw.githubusercontent.com/linz/basemaps-config/master/config/tileset/elevation.json'
      - name: odr_url
        description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/"'
        value: ''
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '2'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: get-location
            templateRef:
              name: tpl-get-location
              template: main

          - name: create-mapsheet
            template: create-mapsheet
            arguments:
              parameters:
                - name: config_file
                  value: '{{workflow.parameters.config_file}}'
                - name: compare
                  # Workaround --compare with empty value will fail so we add the flag inside the input parameter
                  value: '{{= workflow.parameters.odr_url == "" ? "" : "--compare=" + sprig.trimSuffix("/", workflow.parameters.odr_url) + "/collection.json" }}'
                - name: bucket
                  value: '{{tasks.get-location.outputs.parameters.bucket}}'
                - name: key
                  value: '{{tasks.get-location.outputs.parameters.key}}'
            depends: 'get-location.Succeeded'

          - name: group
            templateRef:
              name: tpl-at-group
              template: main
            arguments:
              artifacts:
                - name: input
                  from: '{{ tasks.create-mapsheet.outputs.artifacts.files }}'
              parameters:
                - name: size
                  value: '{{workflow.parameters.group}}'
                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks}}'
            depends: 'create-mapsheet'
            when: "{{= len(sprig.fromJson(tasks['create-mapsheet'].outputs.parameters.file_list)) > 0 }}"

          - name: stac-setup
            templateRef:
              name: tpl-at-stac-setup
              template: main
            arguments:
              parameters:
                - name: gsd
                  value: '1'
                - name: region
                  value: 'new zealand'
                - name: geospatial_category
                  value: 'dem'
                - name: odr_url
                  value: '{{=sprig.trim(workflow.parameters.odr_url)}}'
                - name: version
                  value: '{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
                - name: add_date_in_survey_path
                  value: 'false'
            depends: 'group.Succeeded'

          - name: standardise-validate
            template: standardise-validate
            arguments:
              parameters:
                - name: group_id
                  value: '{{item}}'
                - name: collection_id
                  value: '{{tasks.stac-setup.outputs.parameters.collection_id}}'
                - name: current_datetime
                  value: '{{tasks.stac-setup.finishedAt}}'
                - name: target
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/flat/'
              artifacts:
                - name: group_data
                  from: '{{ tasks.group.outputs.artifacts.output }}'
            depends: 'stac-setup.Succeeded && get-location.Succeeded'
            withParam: '{{ tasks.group.outputs.parameters.output }}'

          - name: create-collection
            template: create-collection
            arguments:
              parameters:
                - name: collection_id
                  value: '{{tasks.stac-setup.outputs.parameters.collection_id}}'
                - name: linz_slug
                  value: '{{tasks.stac-setup.outputs.parameters.linz_slug}}'
                - name: location
                  value: '{{tasks.get-location.outputs.parameters.location}}'
                - name: current_datetime
                  value: '{{tasks.stac-setup.finishedAt}}'
            depends: 'standardise-validate.Succeeded'

          - name: stac-validate
            templateRef:
              name: tpl-at-stac-validate
              template: main
            arguments:
              parameters:
                - name: uri
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/flat/collection.json'
              artifacts:
                - name: stac-result
                  raw:
                    data: '{{tasks.stac-validate.outputs.result}}'
            depends: 'create-collection.Succeeded'

          - name: create-config
            arguments:
              parameters:
                - name: location
                  value: '{{tasks.get-location.outputs.parameters.location}}'
                - name: bucket
                  value: '{{tasks.get-location.outputs.parameters.bucket}}'
                - name: key
                  value: '{{tasks.get-location.outputs.parameters.key}}'
            template: create-config
            depends: 'standardise-validate'

          - name: publish-odr
            templateRef:
              name: publish-odr
              template: main
            when: "'{{workflow.parameters.publish_to_odr}}' == 'true'"
            arguments:
              parameters:
                - name: source
                  value: '{{=sprig.trimSuffix("/", tasks["get-location"].outputs.parameters.location)}}/flat/'
                - name: target_bucket_name
                  value: 'nz-elevation'
                - name: copy_option
                  value: '{{workflow.parameters.copy_option}}'
                - name: ticket
                  value: '{{=sprig.trim(workflow.parameters.ticket)}}'
            depends: 'stac-validate.Succeeded && create-config.Succeeded'

      outputs:
        parameters:
          - name: target
            valueFrom:
              parameter: '{{tasks.get-location.outputs.parameters.location}}'
              default: ''
      # END TEMPLATE `main`

    - name: create-mapsheet
      inputs:
        parameters:
          - name: config_file
          - name: compare
          - name: bucket
          - name: key
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        resources:
          requests:
            cpu: 3000m
            memory: 7.8Gi
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            'mapsheet-coverage',
            '--verbose',
            '--location',
            '{{inputs.parameters.config_file}}',
            '--epsg-code',
            '2193',
            '{{inputs.parameters.compare}}',
          ]
      outputs:
        parameters:
          - name: file_list
            valueFrom:
              path: /tmp/mapsheet-coverage/file-list.json
        artifacts:
          # List of tiff files that need to be processed
          - name: files
            path: /tmp/mapsheet-coverage/file-list.json
            optional: true
            archive:
              none: {}
          - name: layers_source
            path: /tmp/mapsheet-coverage/layers-source.geojson.gz
            optional: true
            archive:
              none: {}
          - name: layers_combined
            path: /tmp/mapsheet-coverage/layers-combined.geojson.gz
            optional: true
            archive:
              none: {}
          # Provenance information for the collection
          - name: capture_dates
            path: /tmp/mapsheet-coverage/capture-dates.geojson
            s3:
              bucket: '{{inputs.parameters.bucket}}'
              key: '{{=sprig.trimSuffix("/", inputs.parameters.key)}}/flat/capture-dates.geojson'
            archive:
              none: {}

    - name: standardise-validate
      nodeSelector:
        karpenter.sh/capacity-type: 'spot'
      inputs:
        parameters:
          - name: group_id
          - name: collection_id
          - name: current_datetime
          - name: target
        artifacts:
          - name: group_data
            path: /tmp/input/
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{=sprig.trim(workflow.parameters.version_topo_imagery)}}'
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
            ephemeral-storage: 3Gi
        volumeMounts:
          - name: ephemeral
            mountPath: '/tmp'
        args:
          - python
          - '/app/scripts/standardise_validate.py'
          - '--from-file'
          - '/tmp/input/{{inputs.parameters.group_id}}.json'
          - '--target'
          - '{{inputs.parameters.target}}'
          - '--preset'
          - 'dem_lerc'
          - '--collection-id'
          - '{{inputs.parameters.collection_id}}'
          - '--create-footprints'
          - 'true'
          - '--source-epsg'
          - '2193'
          - '--target-epsg'
          - '2193'
          - '--gsd'
          - '1'
          - '--odr-url'
          - '{{=sprig.trim(workflow.parameters.odr_url)}}'
          - '--current-datetime'
          - '{{inputs.parameters.current_datetime}}'

    - name: create-collection
      nodeSelector:
        karpenter.sh/capacity-type: 'spot'
      inputs:
        parameters:
          - name: collection_id
          - name: linz_slug
          - name: location
          - name: current_datetime
      outputs:
        artifacts:
          - name: capture-area
            path: '/tmp/capture-area.geojson'
            optional: true
            archive:
              none: {}
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{=sprig.trim(workflow.parameters.version_topo_imagery)}}'
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
        args:
          - python
          - '/app/scripts/collection_from_items.py'
          - '--uri'
          - '{{=sprig.trimSuffix("/", inputs.parameters.location)}}/flat/'
          - '--collection-id'
          - '{{inputs.parameters.collection_id}}'
          - '--linz-slug'
          - '{{inputs.parameters.linz_slug}}'
          - '--odr-url'
          - '{{=sprig.trim(workflow.parameters.odr_url)}}'
          - '--category'
          - 'dem'
          - '--region'
          - 'new-zealand'
          - '--gsd'
          - '1'
          - '--lifecycle'
          - 'ongoing'
          - '--producer'
          - 'Toitū Te Whenua Land Information New Zealand'
          - '--producer-list'
          - ''
          - '--licensor'
          - 'Toitū Te Whenua Land Information New Zealand'
          - '--licensor-list'
          - ''
          - '--concurrency'
          - '25'
          - '--capture-dates'
          - '--current-datetime'
          - '{{inputs.parameters.current_datetime}}'

    - name: create-config
      inputs:
        parameters:
          - name: location
            description: 'Location of the imagery to create config for'
          - name: bucket
          - name: key
      container:
        image: 'ghcr.io/linz/basemaps/cli:{{=sprig.trim(workflow.parameters.version_basemaps_cli)}}'
        command: [node, /app/node_modules/@basemaps/cogify/dist/index.cjs]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.basemaps.json
        args:
          - 'config'
          - '{{=sprig.trimSuffix("/", inputs.parameters.location)}}/flat/'
      outputs:
        parameters:
          - name: url
            description: 'Basemaps URL to view the imagery'
            valueFrom:
              path: '/tmp/cogify/config-url'
          - name: config
            description: 'Location of the config file'
            valueFrom:
              path: '/tmp/cogify/config-path'
        artifacts:
          - name: url
            path: '/tmp/cogify/config-url'
            s3:
              bucket: '{{inputs.parameters.bucket}}'
              key: '{{=sprig.trimSuffix("/", inputs.parameters.key)}}/flat/config-url'
            archive:
              none: {}

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-exit-handler` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-exit-handler
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
