# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: national-hillshade
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: 'spot'
  entrypoint: main
  onExit: exit-handler
  workflowMetadata:
    labels:
      linz.govt.nz/region: 'new-zealand'
    labelsFrom:
      linz.govt.nz/ticket:
        expression: workflow.parameters.ticket
  podMetadata:
    labels:
      linz.govt.nz/category: raster
      linz.govt.nz/data-type: raster
      linz.govt.nz/region: 'new-zealand'
  arguments:
    parameters:
      - name: version_argo_tasks
        description: 'Specify a version of the argo-tasks image to use, e.g. "v4.1" or "latest"'
        value: 'v4'
      - name: version_basemaps_cli
        description: 'Specify a version of the basemaps-cli image to use, e.g. "v7.1" or "latest"'
        value: 'v7'
      - name: version_topo_imagery
        description: 'Specify a version of the topo-imagery image to use, e.g. "v4.8" or "latest"'
        value: 'v7'
      - name: ticket
        description: 'Ticket ID, e.g. "TDE-1130"'
        value: ''
      - name: source
        default: 's3://nz-elevation/new-zealand/new-zealand/dem_1m/2193/'
      - name: odr_url
        description: '(Optional) If an existing dataset add the S3 path to the dataset here to load existing metadata e.g. "s3://nz-elevation/new-zealand/new-zealand/dem-hillshade_1m/2193/"'
        value: ''
      - name: group
        description: 'How many output tiles to process in each standardise-validate task "pod". Change if you have resource or performance issues when standardising a dataset.'
        value: '5'
      - name: publish_to_odr
        description: 'Create a Pull Request for publishing to imagery or elevation ODR bucket'
        value: 'false'
        enum:
          - 'false'
          - 'true'
      - name: hillshade_presets
        value: '["hillshade", "hillshade-igor"]'
      - name: copy_option
        description: 'Do not overwrite existing files with "no-clobber", "force" overwriting files in the target location, or "force-no-clobber" overwriting only changed files, skipping unchanged files'
        value: '--force-no-clobber'
        enum:
          - '--no-clobber'
          - '--force'
          - '--force-no-clobber'
      #      - name: create_capture_area
      #        value: 'true'
      #        enum:
      #          - 'false'
      #          - 'true'
      - name: gsd
        value: '1'
      #      - name: scale_to_resolution
      #        description: 'Scale output TIFFs to x,y resolution (e.g. 1,1 - leave blank for no scaling)'
      #        value: '1,1'
      - name: source_epsg
        value: '2193'
      - name: target_epsg
        value: '2193'
      - name: include
        description: 'Regular expression pattern match for paths/files to include e.g ".tiff?$"'
        value: '.tiff?$'
      - name: scale
        description: 'Scale of the standardised output imagery'
        value: '50000'
        enum:
          - '500'
          - '1000'
          - '2000'
          - '5000'
          - '10000'
          - '50000'
          - 'None'
      - name: target_bucket_name
        description: 'The ODR bucket name to publish to'
        value: 'nz-elevation'
        enum:
          - 'nz-imagery'
          - 'nz-elevation'
      - name: region
        value: 'new-zealand'
      #      - name: gdal_compression_preset
      #        default: 'dem_lerc'
      - name: cutline
        default: 's3://linz-basemaps-source/cutline/2020-05-07-cutline-nz-coasts-rural-and-urban.geojson'

  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: create-hillshades
            templateRef:
              name: tpl-hillshade
              template: main
            arguments:
              parameters:
                - name: ticket
                  value: '{{workflow.parameters.ticket}}'
                - name: source
                  value: '{{workflow.parameters.source}}'
                - name: odr_url
                  value: '{{workflow.parameters.odr_url}}'
                - name: group
                  value: '{{workflow.parameters.group}}'
                - name: publish_to_odr
                  value: '{{workflow.parameters.publish_to_odr}}'
                - name: copy_option
                  value: '{{workflow.parameters.copy_option}}'
                - name: compression
                  value: '{{workflow.parameters.gdal_compression_preset}}'
                - name: gsd
                  value: '{{workflow.parameters.gsd}}'
                - name: source_epsg
                  value: '{{workflow.parameters.source_epsg}}'
                - name: target_epsg
                  value: '{{workflow.parameters.target_epsg}}'
                - name: include
                  value: '{{workflow.parameters.include}}'
                - name: scale
                  value: '{{workflow.parameters.scale}}'
                - name: target_bucket_name
                  value: '{{workflow.parameters.target_bucket_name}}'
                - name: region
                  value: '{{workflow.parameters.region}}'
                - name: hillshade_preset
                  value: '{{item}}'
            withParam: '{{workflow.parameters.hillshade_presets}}'

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-exit-handler` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-exit-handler
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
