# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: 'argoproj.io/v1alpha1'
kind: 'Workflow'
metadata:
  generateName: 'test-topo-imagery-'
  labels:
    linz.govt.nz/category: 'test'
    linz.govt.nz/data-type: 'raster'
spec:
  serviceAccountName: 'workflow-runner-sa'
  podGC:
    strategy: 'OnPodCompletion' # Delete pod once its finished
  entrypoint: 'test-script'
  podMetadata:
    labels:
      linz.govt.nz/category: 'test'
      linz.govt.nz/data-type: 'raster'
  arguments:
    parameters:
      - name: 'version_topo_imagery'
        value: 'latest'
  templateDefaults:
    container:
      imagePullPolicy: 'Always'
      image: ''
  templates:
    - name: 'test-script'
      script:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{workflow.parameters.version_topo_imagery}}'
        args:
          - 'python'
        source: |
          # Put your code below
