# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: 'argoproj.io/v1alpha1'
kind: 'WorkflowTemplate'
metadata:
  # Template calling linz/topo-imagery for its main task (generate-hillshade)
  # see https://github.com/linz/topo-imagery/pull/1253
  name: 'tpl-create-hillshade'
  labels:
    linz.govt.nz/category: 'raster'
spec:
  templateDefaults:
    container:
      imagePullPolicy: 'Always'
      image: ''
  entrypoint: 'main'
  templates:
    - name: 'main'
      inputs:
        parameters:
          - name: 'source'
            description: 's3 path to where the TIFF files to generate hillshade from are stored.'
          - name: 'scale'
            description: 'Scale of the source data.'
          - name: 'group'
            description: 'Number of tiles to group together.'
          - name: 'version_argo_tasks'
            description: 'Version of the argo-tasks image to use.'
            default: 'v4'
          - name: 'version_topo_imagery'
            description: 'Version of the topo-imagery image to use.'
            default: 'v7'
          - name: 'target'
            description: 's3 path to where the hillshade tiles will be stored. The different hillshade types will be stored in subdirectories using the preset name.'
          - name: 'preset'
            description: 'List of hillshade types to generate. Expect a list of strings.'
            default: '["greyscale", "igor"]'
      dag:
        tasks:
          - name: 'tile-index-validate'
            templateRef:
              name: 'tpl-at-tile-index-validate'
              template: 'main'
            arguments:
              parameters:
                - name: 'scale'
                  value: '{{inputs.parameters.scale}}'
                - name: 'include'
                  value: '.tiff?$'
                - name: 'source'
                  value: '{{=sprig.trim(inputs.parameters.source)}}'
                - name: 'source_epsg'
                  value: '2193'
                - name: 'validate'
                  value: 'false'
                - name: 'retile'
                  value: 'true'
                - name: 'preset'
                  value: 'dem_lerc'
                - name: 'version'
                  value: '{{= inputs.parameters.version_argo_tasks}}'

          - name: 'group'
            templateRef:
              name: 'tpl-at-group'
              template: 'main'
            arguments:
              artifacts:
                - name: 'input'
                  from: '{{ tasks.tile-index-validate.outputs.artifacts.files }}'
              parameters:
                - name: 'size'
                  value: '{{inputs.parameters.group}}'
                - name: 'version'
                  value: '{{= inputs.parameters.version_argo_tasks}}'
            depends: 'tile-index-validate'

          - name: 'hillshade-preset'
            template: 'hillshade-preset'
            arguments:
              parameters:
                - name: 'group_id'
                  value: '{{item}}'
                - name: 'target'
                  value: '{{inputs.parameters.target}}'
                - name: 'preset'
                  value: '{{inputs.parameters.preset}}'
                - name: 'version_topo_imagery'
                  value: '{{inputs.parameters.version_topo_imagery}}'
              artifacts:
                - name: 'group_data'
                  from: '{{ tasks.group.outputs.artifacts.output }}'
            depends: 'group'
            withParam: '{{ tasks.group.outputs.parameters.output }}'

    - name: 'hillshade-preset'
      inputs:
        parameters:
          - name: 'group_id'
          - name: 'target'
          - name: 'preset'
          - name: 'version_topo_imagery'
        artifacts:
          - name: 'group_data'
      steps:
        - - name: 'generate-hillshade'
            template: 'generate-hillshade'
            arguments:
              parameters:
                - name: 'group_id'
                  value: '{{inputs.parameters.group_id}}'
                - name: 'target'
                  value: '{{inputs.parameters.target}}'
                - name: 'preset'
                  value: '{{item}}'
                - name: 'version_topo_imagery'
                  value: '{{inputs.parameters.version_topo_imagery}}'
              artifacts:
                - name: 'group_data'
                  from: '{{inputs.artifacts.group_data}}'
            withParam: '{{inputs.parameters.preset}}'

    - name: 'generate-hillshade'
      nodeSelector:
        karpenter.sh/capacity-type: 'spot'
      inputs:
        parameters:
          - name: 'group_id'
          - name: 'target'
          - name: 'preset'
          - name: 'version_topo_imagery'
        artifacts:
          - name: 'group_data'
            path: '/tmp/input/'
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{=sprig.trim(inputs.parameters.version_topo_imagery)}}'
        resources:
          requests:
            memory: '7.8Gi'
            cpu: '15000m'
            ephemeral-storage: '29.5Gi'
        volumeMounts:
          # This volume must be defined in the workflow calling this workflowTemplate
          - name: 'ephemeral'
            mountPath: '/tmp'
        args:
          - 'python'
          - '/app/scripts/generate_hillshade.py'
          - '--from-file'
          - '/tmp/input/{{inputs.parameters.group_id}}.json'
          - '--target'
          - '{{=sprig.trimSuffix("/", inputs.parameters.target)}}/{{inputs.parameters.preset}}/'
          - '--preset'
          - '{{inputs.parameters.preset}}'
