# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-national-coastal-dem
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  schedule: '0 6 * * 1-5' # At 06:00 AM, Monday through Friday
  timezone: 'NZ'
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: true # Temporarily suspend the workflow to prevent it from running automatically.
  workflowMetadata:
    labels:
      linz.govt.nz/ticket: ''
  workflowSpec:
    podMetadata:
      labels:
        linz.govt.nz/category: raster
        linz.govt.nz/data-type: raster
        linz.govt.nz/region: 'new-zealand'
    workflowTemplateRef:
      name: national-elevation
    arguments:
      parameters:
        - name: 'config_file'
          value: 's3://linz-workflows-scratch/pfo/coastal-test.json'
        - name: 'odr_url'
          value: ''
        - name: geospatial_category
          value: 'dem'
        - name: publish_to_odr
          value: 'true'
        - name: 'target_bucket_name'
          value: 'nz-coastal'
        - name: 'copy_option'
          value: '--force-no-clobber'
        - name: 'ticket'
          value: ''
