# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-copy-restore
  labels:
    linz.govt.nz/category: storage
spec:
  schedule: '0 6,12 * * 1-5' # At 6:00AM and 12:00PM, Monday through Friday
  timezone: 'NZ'
  startingDeadlineSeconds: 3600 # Allow 1 hour delay if the workflow-controller clashes during the starting time.
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false
  workflowSpec:
    entrypoint: main
    podMetadata:
      labels:
        linz.govt.nz/category: storage
    templates:
      - name: main
        retryStrategy:
          expression: 'false'
        steps:
          - - name: copy-restore
              templateRef:
                name: copy-restore
                template: main
              arguments:
                parameters:
                  - name: version_argo_tasks
                    value: 'v4'
                  - name: reports_location
                    value: 's3://linz-workflows-scratch/restore/requests/'
