# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-topo-maps-coastline-sea-polygon
  labels:
    linz.govt.nz/category: topo-maps
    linz.govt.nz/data-type: vector
spec:
  schedules:
    - '31 06 * * 1-5' # 6.31 AM Monday to Friday
  timezone: 'NZ'
  startingDeadlineSeconds: 3600 # Allow 1 hour delay if the workflow-controller clashes during the starting time.
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false
  workflowSpec:
    podMetadata:
      labels:
        linz.govt.nz/category: topo-maps
        linz.govt.nz/data-type: vector
    arguments:
      parameters:
        - name: version_kart_cli
          value: 'latest'
        - name: coastline
          value: 's3://linz-topography-nonprod/data/coastline/latest/collection.json'
        - name: island
          value: 's3://linz-topography-nonprod/data/island/latest/collection.json'
        - name: coastline_island
          value: 's3://linz-topography-nonprod/data/nztopo50_coastline_island/latest/collection.json'
        - name: target
          value: 's3://linz-topography-nonprod/'
        - name: latest
          value: 'true'
        - name: commit
          value: 'true'
    entrypoint: main
    templates:
      - name: main
        dag:
          tasks:
            - name: get-location
              templateRef:
                name: tpl-get-location
                template: main
            - name: coastline-polygon
              template: run-coastline-polygon
              depends: get-location.Succeeded
              arguments:
                parameters:
                  - name: location
                    value: '{{tasks.get-location.outputs.parameters.location}}/coastline'
            - name: sea-polygon
              template: run-sea-polygon
              depends: coastline-polygon.Succeeded
              arguments:
                parameters:
                  - name: location
                    value: '{{tasks.get-location.outputs.parameters.location}}/sea'

      - name: run-coastline-polygon
        inputs:
          parameters:
            - name: location
        dag:
          tasks:
            - name: coastline-polygon
              templateRef:
                name: topographic-coastline-polygon
                template: coastline-polygon
              arguments:
                parameters:
                  - name: version_kart_cli
                    value: '{{workflow.parameters.version_kart_cli}}'
                  - name: coastline
                    value: '{{workflow.parameters.coastline}}'
                  - name: island
                    value: '{{workflow.parameters.island}}'
                  - name: output
                    value: '{{inputs.parameters.location}}'
            - name: stac-push
              templateRef:
                name: topographic-coastline-polygon
                template: stac-push
              depends: coastline-polygon.Succeeded
              arguments:
                parameters:
                  - name: version_kart_cli
                    value: '{{workflow.parameters.version_kart_cli}}'
                  - name: source
                    value: '{{inputs.parameters.location}}'
                  - name: target
                    value: '{{workflow.parameters.target}}'
                  - name: latest
                    value: '{{workflow.parameters.latest}}'
                  - name: commit
                    value: '{{workflow.parameters.commit}}'

      - name: run-sea-polygon
        inputs:
          parameters:
            - name: location
        dag:
          tasks:
            - name: sea-polygon
              templateRef:
                name: topographic-sea-polygon
                template: sea-polygon
              arguments:
                parameters:
                  - name: version_kart_cli
                    value: '{{workflow.parameters.version_kart_cli}}'
                  - name: coastline
                    value: '{{workflow.parameters.coastline_island}}'
                  - name: output
                    value: '{{inputs.parameters.location}}'
            - name: stac-push
              templateRef:
                name: topographic-sea-polygon
                template: stac-push
              depends: sea-polygon.Succeeded
              arguments:
                parameters:
                  - name: version_kart_cli
                    value: '{{workflow.parameters.version_kart_cli}}'
                  - name: source
                    value: '{{inputs.parameters.location}}'
                  - name: target
                    value: '{{workflow.parameters.target}}'
                  - name: latest
                    value: '{{workflow.parameters.latest}}'
                  - name: commit
                    value: '{{workflow.parameters.commit}}'
