# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-stac-validate-fast
  labels:
    linz.govt.nz/category: stac
spec:
  schedule: '0 15 * * 1-5' # At 3:00 PM, Monday through Friday
  timezone: 'NZ'
  startingDeadlineSeconds: 3600 # Allow 1 hour delay if the workflow-controller clashes during the starting time.
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: true
  workflowSpec:
    entrypoint: main
    onExit: exit-handler
    podMetadata:
      labels:
        linz.govt.nz/category: stac
    arguments:
      parameters:
        - name: checksum_assets
          value: 'false'
        - name: 'checksum_links'
          value: 'true'
    templates:
      - name: main
        retryStrategy:
          expression: 'false'
        steps:
          - - name: stac-validate-imagery
              templateRef:
                name: tpl-at-stac-validate
                template: main
              arguments:
                parameters:
                  - name: 'uri'
                    value: 's3://nz-imagery/catalog.json'
                  - name: 'checksum_assets'
                    value: '{{workflow.parameters.checksum_assets}}'
                  - name: 'checksum_links'
                    value: '{{workflow.parameters.checksum_links}}'
            - name: stac-validate-elevation
              templateRef:
                name: tpl-at-stac-validate
                template: main
              arguments:
                parameters:
                  - name: 'uri'
                    value: 's3://nz-elevation/catalog.json'
                  - name: 'checksum_assets'
                    value: '{{workflow.parameters.checksum_assets}}'
                  - name: 'checksum_links'
                    value: '{{workflow.parameters.checksum_links}}'
            - name: stac-validate-coastal
              templateRef:
                name: tpl-at-stac-validate
                template: main
              arguments:
                parameters:
                  - name: 'uri'
                    value: 's3://nz-coastal/catalog.json'
                  - name: 'checksum_assets'
                    value: '{{workflow.parameters.checksum_assets}}'
                  - name: 'checksum_links'
                    value: '{{workflow.parameters.checksum_links}}'
      - name: exit-handler
        retryStrategy:
          limit: '0' # `tpl-log-notification` retries itself
        steps:
          - - name: exit
              templateRef:
                name: tpl-log-notification
                template: main
              arguments:
                parameters:
                  - name: workflow_status
                    value: '{{workflow.status}}'
                  - name: workflow_parameters
                    value: '{{workflow.parameters}}'
