# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-national-dsm
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  schedule: '0 6 * * 1-5' # At 06:00 AM, Monday through Friday
  timezone: 'NZ'
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  workflowMetadata:
    labels:
      linz.govt.nz/ticket: 'TDE-1454'
  workflowSpec:
    podMetadata:
      labels:
        linz.govt.nz/category: raster
        linz.govt.nz/data-type: raster
        linz.govt.nz/region: 'new-zealand'
    workflowTemplateRef:
      name: national-elevation
    arguments:
      parameters:
        - name: 'config_file'
          value: 'https://raw.githubusercontent.com/linz/basemaps-config/master/config/tileset/elevation.dsm.json'
        - name: 'odr_url'
          value: 's3://nz-elevation/new-zealand/new-zealand/dsm_1m/2193/'
        - name: geospatial_category
          value: 'dsm'
        - name: publish_to_odr
          value: 'true'
        - name: 'copy_option'
          value: '--force-no-clobber'
        - name: 'ticket'
          value: 'TDE-1454'
