# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-topo-maps-rock-line
  labels:
    linz.govt.nz/category: topo-maps
    linz.govt.nz/data-type: vector
spec:
  schedules:
    - '15 06 * * 1-5' # 6.15 AM Monday to Friday
  timezone: 'NZ'
  startingDeadlineSeconds: 3600 # Allow 1 hour delay if the workflow-controller clashes during the starting time.
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false
  workflowSpec:
    podMetadata:
      labels:
        linz.govt.nz/category: topo-maps
        linz.govt.nz/data-type: vector
    workflowTemplateRef:
      name: topographic-rock-line
    arguments:
      parameters:
        - name: 'contour'
          value: 's3://linz-topography-nonprod/data/contour/latest/collection.json'
        - name: 'landcover'
          value: 's3://linz-topography-nonprod/data/landcover/latest/collection.json'
        - name: 'target'
          value: 's3://linz-topography-nonprod/'

        - name: marine
          value: 's3://linz-topography-nonprod/data/marine/latest/collection.json'
        - name: coastline
          value: 's3://linz-topography-nonprod/data/coastline/latest/collection.json'
        - name: island
          value: 's3://linz-topography-nonprod/data/island/latest/collection.json'
        - name: water
          value: 's3://linz-topography-nonprod/data/water/latest/collection.json'
        - name: target
          description: Path or s3 of the target directory to write to.
          value: 's3://linz-topography-nonprod/'
