# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.10/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-national-dem-coastal
  labels:
    linz.govt.nz/category: raster
    linz.govt.nz/data-type: raster
spec:
  schedules:
    - '0 6 * * 1-5' # At 06:00 AM, Monday through Friday
  timezone: 'NZ'
  concurrencyPolicy: 'Allow'
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: false
  workflowMetadata:
    labels:
      linz.govt.nz/ticket: 'TDE-1524'
  workflowSpec:
    podMetadata:
      labels:
        linz.govt.nz/category: raster
        linz.govt.nz/data-type: raster
        linz.govt.nz/region: 'new-zealand'
    workflowTemplateRef:
      name: national-elevation
    arguments:
      parameters:
        - name: 'config_file'
          value: 'https://raw.githubusercontent.com/linz/basemaps-config/refs/heads/master/config/tileset/elevation.coastal.json'
        - name: 'odr_url'
          value: 's3://nz-coastal/new-zealand/new-zealand/dem_1m/2193/'
        - name: geospatial_category
          value: 'dem'
        - name: domain
          value: 'coastal'
        - name: publish_to_odr
          value: 'true'
        - name: 'target_bucket_name'
          value: 'nz-coastal'
        - name: 'copy_option'
          value: '--force-no-clobber'
        - name: 'ticket'
          value: 'TDE-1524'
