# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: topographic-data-preparation
  labels:
    linz.govt.nz/category: topo-maps
    linz.govt.nz/data-type: vector
spec:
  entrypoint: main
  onExit: exit-handler
  podMetadata:
    labels:
      linz.govt.nz/category: topo-maps
      linz.govt.nz/data-type: vector
  arguments:
    parameters:
      - name: version_kart_cli
        description: Version of the kart CLI docker container to use
        value: 'latest'

      - name: contour
        description: S3 path of source parquet contour data stac collection.
        value: 's3://linz-topography-nonprod/data/contour/latest/collection.json'

      - name: landcover
        description: S3 path of source parquet landcover data stac collection.
        value: 's3://linz-topography-nonprod/data/landcover/latest/collection.json'

      - name: target
        description: Path or s3 of the target directory to write generated map sheets.
        value: 's3://linz-topography-scratch-nonprod/'
        enum:
          - 's3://linz-topography-scratch-nonprod/'
          - 's3://linz-topography-nonprod/'
          - 's3://linz-topography/'

      - name: latest
        description: Whether to push to stac with latest strategy.
        value: 'true'
        enum:
          - 'true'
          - 'false'

      - name: commit
        description: Whether to push to write the output to target bucket
        value: 'true'
        enum:
          - 'true'
          - 'false'

  templates:
    - name: main
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: get-location
            templateRef:
              name: tpl-get-location
              template: main

          - name: contour-with-landcover
            template: contour-with-landcover
            depends: get-location
            arguments:
              parameters:
                - name: version_kart_cli
                  value: '{{ workflow.parameters.version_kart_cli }}'
                - name: contour
                  value: '{{ workflow.parameters.contour }}'
                - name: landcover
                  value: '{{ workflow.parameters.landcover }}'
                - name: output
                  value: '{{ tasks.get-location.outputs.parameters.location }}'

          - name: stac-push
            template: stac-push
            depends: contour-with-landcover
            arguments:
              parameters:
                - name: version_kart_cli
                  value: '{{ workflow.parameters.version_kart_cli }}'
                - name: source
                  value: '{{ tasks.get-location.outputs.parameters.location }}'
                - name: target
                  value: '{{ workflow.parameters.target }}'
                - name: latest
                  value: '{{ workflow.parameters.latest }}'
                - name: commit
                  value: '{{ workflow.parameters.commit }}'

    - name: contour-with-landcover
      inputs:
        parameters:
          - name: version_kart_cli
          - name: contour
          - name: landcover
          - name: output
      container:
        image: ghcr.io/linz/topographic-system/kart:{{ inputs.parameters.version_kart_cli }}
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.topography.json
          - name: ENVIRONMENT
            value: nonprod
        resources:
          requests:
            memory: 30Gi
            cpu: 15000m
        args:
          - 'contour-with-landcover'
          - '--contour={{ inputs.parameters.contour }}'
          - '--landcover={{ inputs.parameters.landcover }}'
          - '--output={{ inputs.parameters.output }}'

    - name: stac-push
      inputs:
        parameters:
          - name: version_kart_cli
          - name: source
          - name: target
          - name: latest
          - name: commit
      container:
        image: ghcr.io/linz/topographic-system/kart:{{ inputs.parameters.version_kart_cli }}
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
        imagePullPolicy: Always
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.topography.json
        args:
          - stac-push
          - --source={{= sprig.trimSuffix("/", inputs.parameters.source) }}/catalog.json
          - --target={{ inputs.parameters.target }}
          - --category=data
          - --strategy=date
          - '{{= inputs.parameters.latest == "true" ? "--strategy=latest" : "" }}'
          - --commit={{ inputs.parameters.commit }}

    - name: exit-handler
      retryStrategy:
        limit: '0' # `tpl-log-notification` retries itself
      steps:
        - - name: exit
            templateRef:
              name: tpl-log-notification
              template: main
            arguments:
              parameters:
                - name: workflow_status
                  value: '{{workflow.status}}'
                - name: workflow_parameters
                  value: '{{workflow.parameters}}'
