---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: imagery-non-visual-qa-v0.2.0-20
spec:
  serviceAccountName: workflow-runner-sa
  workflowMetadata:
    annotations:
      fluentbit.io/parser: json
  podGC:
    strategy: OnPodCompletion # Delete pod once its finished
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: ""
      - name: filter
        value: ".tiff?$"
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: "{{workflow.parameters.filter}}"
          - name: non-visual-qa
            template: non-visual-qa
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: "aws-list"
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
        image: ghcr.io/linz/basemaps/cli:v6.29.0-3-gb4dec98c
        command: [node, index.cjs]
        args:
          [
            "-V",
            "list",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--group",
            "100",
            "--output",
            "/tmp/file_list.json",
            "--config",
            "linz-bucket-config",
            "{{inputs.parameters.uri}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: non-visual-qa
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-20-ged4d623
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
        command:
          - python
          - "/app/non_visual_qa.py"
        args:
          - "--source"
          - "{{inputs.parameters.file}}"
