---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: imagery-non-visual-qa-
spec:
  serviceAccountName: workflow-runner-sa
  podGC:
    strategy: OnPodCompletion # Delete pod once its finished
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: uri
        value: "s3://linz-imagery-staging/RGBi4/tasman_rural_2020_0.3m_a_RGBI/tif/"
      - name: filter
        value: "2020_BQ24_5000_*1.tif"
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list
            arguments:
              parameters:
                - name: uri
                  value: "{{workflow.parameters.uri}}"
                - name: filter
                  value: "{{workflow.parameters.filter}}"
          - name: non-visual-qa
            template: non-visual-qa
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: "aws-list"
            withParam: "{{tasks.aws-list.outputs.parameters.files}}"
    - name: aws-list
      inputs:
        parameters:
          - name: uri
          - name: filter
      container:
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
        image: ghcr.io/linz/basemaps/cli:v6.29.0-3-gb4dec98c
        command: [node, index.cjs]
        args:
          [
            "-V",
            "list",
            "--filter",
            "{{inputs.parameters.filter}}",
            "--output",
            "/tmp/file_list.json",
            "--config",
            "linz-bucket-config",
            "{{inputs.parameters.uri}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: non-visual-qa
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/topo-imagery:v0.2.0-14-g5387093
        resources:
          requests:
            memory: 2Gi
            cpu: 2000m
        command:
          - python
          - "/app/non_visual_qa.py"
        args:
          - "--source"
          - "{{inputs.parameters.file}}"
