---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: publish-copy-v1.0.0-46
  namespace: argo
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: source
        value: "s3://linz-imagery-staging/test/sample/"
      - name: target
        value: "s3://linz-imagery-staging/test/sample_target/"
      - name: include
        value: ".tiff?$|.json$|.tfw$"
      - name: copy-option
        value: "--no-clobber"
        enum:
          - "--no-clobber"
          - "--force"
      - name: flatten
        value: "--flatten"
        enum:
          - "--flatten"
          - ""
  templates:
    - name: main
      dag:
        tasks:
          - name: create-manifest
            template: create-manifest
            arguments:
              parameters:
                - name: source
                  value: "{{workflow.parameters.source}}"
                - name: target
                  value: "{{workflow.parameters.target}}"
                - name: include
                  value: "{{workflow.parameters.include}}"
                - name: flatten
                  value: "{{workflow.parameters.flatten}}"
          - name: copy
            template: copy
            arguments:
              parameters:
                - name: file
                  value: "{{item}}"
            depends: "create-manifest"
            withParam: "{{tasks.create-manifest.outputs.parameters.files}}"
    - name: create-manifest
      inputs:
        parameters:
          - name: source
          - name: target
          - name: include
          - name: flatten
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-46-gf39162d
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "create-manifest",
            "--verbose",
            "{{inputs.parameters.flatten}}",
            "--include",
            "{{inputs.parameters.include}}",
            "--group",
            "1000",
            "--group-size",
            "100Gi",
            "--output",
            "/tmp/file_list.json",
            "--target",
            "{{inputs.parameters.target}}",
            "{{inputs.parameters.source}}",
          ]
      outputs:
        parameters:
          - name: files
            valueFrom:
              path: /tmp/file_list.json
    - name: copy
      retryStrategy:
        limit: "2"
      inputs:
        parameters:
          - name: file
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-46-gf39162d
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config.json
        args:
          [
            "copy",
            "{{workflow.parameters.copy-option}}",
            "{{inputs.parameters.file}}",
          ]
