---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-amfage-imagery-standardising-publish-import-
  namespace: argo
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  synchronization:
    semaphore:
      configMapKeyRef:
        name: semaphores
        key: standardising
  arguments:
    parameters:
      - name: cutline # optional standardising cutline
        value: ""
      - name: compression
        value: "webp"
      - name: group
        value: "50"
      - name: copy-option
        value: "--no-clobber"
      - name: include
        value: ".tiff?$"
      - name: version-argo-tasks
        value: "v2"
      - name: version-basemaps-cli
        value: "v6"
      - name: version-topo-imagery
        value: "v0"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: main
      steps:
        - - name: standardise
            templateRef:
              name: imagery-standardising
              template: main
        - - name: publish
            templateRef:
              name: publish-copy
              template: main
            arguments:
              parameters:
                - name: source
                  value: "{{steps.standardise.outputs.parameters.target}}flat/"
                - name: include
                  value: ".tiff?$|.json$"
        # - - name: import # uncomment this stanza for basemaps imagery import and amend as necessary. All other inputs should be workflow parameters
        #     templateRef:
        #       name: basemaps-imagery-import
        #       template: main
        #     arguments:
        #       parameters:
        #         - name: source
        #           value: "{{workflow.parameters.target}}"
        #         - name: target
        #           value: "linz-basemaps" # change to "linz-basemaps-staging" for staging environment
        #         - name: cutline
        #           value: "s3://linz-basemaps-source/cutline/2020-05-07-cutline-nz-coasts-rural-and-urban.geojson"
  volumes:
    - name: ephemeral
      emptyDir: {}
    # - name: secret-vol # uncomment for basemaps imagery import
    #   secret:
    #     secretName: github
