apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-topo-imagery-v1-
spec:
  serviceAccountName: workflow-runner-sa
  podGC:
    strategy: OnPodCompletion # Delete pod once its finished
  entrypoint: test-script
  arguments:
    parameters:
      - name: version-topo-imagery
        value: "latest"
  templateDefaults:
    container:
      imagePullPolicy: Always
  templates:
    - name: test-script
      script:
        image: ghcr.io/linz/topo-imagery:{{workflow.parameters.version-topo-imagery}}
        command: [python]
        source: |
          import sys

          # Because Argo Workflow executes the script under "/argo/staging/script"
          sys.path.append("/app/scripts/")

          # Put your code below
