---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tileset-validate-v1.0.0-43
  namespace: argo
spec:
  nodeSelector:
    karpenter.sh/capacity-type: "spot"
  entrypoint: main
  arguments:
    parameters:
      - name: processed-imagery-path
        value: "s3://linz-imagery-staging/test/tileset-validate/flat"
  templates:
    - name: main
      dag:
        tasks:
          - name: tileset-validate
            template: tileset-validate
            arguments:
              parameters:
                - name: processed-imagery-path
                  value: "{{workflow.parameters.processed-imagery-path}}"
              artifacts:
                - name: tileset-validate-result
                  raw:
                    data: "{ { tasks.tileset-validate.outputs.result } }"
    - name: tileset-validate
      inputs:
        parameters:
          - name: processed-imagery-path
      container:
        image: ghcr.io/linz/argo-tasks:v1.0.0-43-g09ca6ea
        command: [node, /app/index.js]
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          [
            "tileset-validate",
            "--verbose",
            "{{inputs.parameters.processed-imagery-path}}",
          ]
