apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-tiv-component-
spec:
  arguments:
    parameters:
      - name: version_argo_tasks
        value: 'v2.10.0-3-g83e7420'
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: tile-index-validate
            templateRef:
              name: tpl-at-tile-index-validate
              template: main

            arguments:
              parameters:
                - name: scale
                  value: 5000

                - name: source
                  value: s3://linz-topographic-upload/skyvuw/SN9457/

                - name: source_epsg
                  value: 2193

                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks }}'

          - name: group
            templateRef:
              name: tpl-at-group
              template: main

            arguments:
              artifacts:
                - name: input
                  from: '{{ tasks.tile-index-validate.outputs.artifacts.files }}'

              parameters:
                - name: size
                  value: 5

                - name: version
                  value: '{{= workflow.parameters.version_argo_tasks }}'

            depends: 'tile-index-validate'

          - name: process
            template: echo
            withParam: '{{ tasks.group.outputs.parameters.output }}'
            arguments:
              parameters:
                - name: echo
                  value: '{{ item }}'
            depends: 'group'

    - name: echo
      inputs:
        parameters:
          - name: echo
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{= workflow.parameters.version_argo_tasks }}'
        command: [echo]
        args:
          - '{{inputs.parameters.echo}}'
