# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: tpl-topographic-sheet-produce
  labels:
    linz.govt.nz/category: topo-maps
    linz.govt.nz/data-type: raster
spec:
  entrypoint: main
  podMetadata:
    labels:
      linz.govt.nz/category: topo-maps
      linz.govt.nz/data-type: raster
  arguments:
    parameters:
      - name: version_map_produce_cli
        description: Version of the map produce CLI docker container to use
        value: 'latest'

      - name: project
        description: Path or s3 of QGIS Project to use for generate map sheets.
        value: 's3://linz-topography-nonprod/qgis/latest/nztopo50map/nz-topo50-map.json'

      - name: layout
        description: Qgis project Layout name to use for export.
        value: 'tiff-50'

      - name: map_sheet_layer
        description: Topo Map Sheet Layer name to use.
        value: 'nz_topo50_map_sheet'

      - name: output
        description: Path or s3 of the output directory to write generated map sheets.
        value: 's3://linz-topography-scratch-nonprod/'

      - name: format
        description: Export format as pdf, tiff, or geotiff
        value: 'tiff'
        enum:
          - 'pdf'
          - 'tiff'
          - 'geotiff'

      - name: dpi
        description: Path or s3 of the output directory to write generated map sheets.
        value: '300'

      - name: map-sheets
        description: Map Sheet Codes to process, json array
        value: '["AX29", "AX30", "AX31"]'

  templates:
    - name: main
      inputs:
        parameters:
          - name: version_map_produce_cli
            value: '{{ workflow.parameters.version_map_produce_cli }}'
          - name: project
            value: '{{ workflow.parameters.project }}'
          - name: layout
            value: '{{ workflow.parameters.layout }}'
          - name: map_sheet_layer
            value: '{{ workflow.parameters.map_sheet_layer }}'
          - name: output
            value: '{{ workflow.parameters.output }}'
          - name: format
            value: '{{ workflow.parameters.format }}'
          - name: dpi
            value: '{{ workflow.parameters.dpi }}'
          - name: map-sheets
            value: '{{ workflow.parameters.map-sheets }}'
      retryStrategy:
        expression: 'false'
      dag:
        tasks:
          - name: sheet-produce
            template: sheet-produce
            arguments:
              parameters:
                - name: version_map_produce_cli
                  value: '{{ inputs.parameters.version_map_produce_cli }}'
                - name: project
                  value: '{{ inputs.parameters.project }}'
                - name: layout
                  value: '{{ inputs.parameters.layout }}'
                - name: map_sheet_layer
                  value: '{{ inputs.parameters.map_sheet_layer }}'
                - name: output
                  value: '{{ inputs.parameters.output }}'
                - name: format
                  value: '{{ inputs.parameters.format }}'
                - name: dpi
                  value: '{{ inputs.parameters.dpi }}'
                - name: map-sheets
                  value: '{{ inputs.parameters.map-sheets }}'

    - name: sheet-produce
      inputs:
        parameters:
          - name: version_map_produce_cli
          - name: project
          - name: layout
          - name: map_sheet_layer
          - name: output
          - name: format
          - name: dpi
          - name: map-sheets
      container:
        image: ghcr.io/linz/topographic-system/map:{{ inputs.parameters.version_map_produce_cli }}
        imagePullPolicy: Always
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config-write.topography.json
        command: [bash, -c]
        args:
          - |
            echo '{{ inputs.parameters.map-sheets }}' > map-sheets.json
            node src/index.ts produce --from-file=map-sheets.json --project='{{ inputs.parameters.project }}' --layout='{{ inputs.parameters.layout }}' --map-sheet-layer='{{ inputs.parameters.map_sheet_layer }}' --output='{{ inputs.parameters.output }}' --format='{{ inputs.parameters.format }}' --dpi='{{ inputs.parameters.dpi }}'
