# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template to log the workflow status and its parameters.
  name: tpl-exit-handler
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: workflow_status
            description: Status of the workflow
          - name: workflow_parameters
            description: Parameters of the workflow
          - name: version_argo_tasks
            description: Version of argo-tasks to use
            default: 'v4'
      script:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(inputs.parameters.version_argo_tasks)}}'
        command: [node]
        source: |
          let parameters = {};
          {{= inputs.parameters.workflow_parameters }}.forEach((pair) => (parameters[pair.name] = pair.value));

          console.log(
            JSON.stringify({
              time: Date.now(),
              level: 20,
              pid: 1,
              msg: 'Workflow:{{inputs.parameters.workflow_status}}',
              parameters,
            }),
          );
