# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template to output the locaton of the workflow S3 artifact root directory.
  name: tpl-get-location
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: version_argo_tasks
            description: Version of argo-tasks to use
            default: 'v5'
          - name: artifact_key
            description: Key of the artifact in S3. Must match the `keyFormat` (without pod name) used in Argo Workflows artifact repository configuration.
            default: '{{workflow.creationTimestamp.Y}}-{{workflow.creationTimestamp.m}}/{{workflow.creationTimestamp.d}}-{{workflow.name}}'
      outputs:
        parameters:
          - name: location
            valueFrom:
              path: '/tmp/location'
          - name: bucket
            valueFrom:
              path: '/tmp/bucket'
          - name: key
            valueFrom:
              path: '/tmp/key'
      script:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(inputs.parameters.version_argo_tasks)}}'
        envFrom:
          - configMapRef:
              name: artifact-config
        command: [node]
        source: |
          const fs = require('node:fs');

          const key = '{{inputs.parameters.artifact_key}}';
          const bucket = process.env.ARTIFACT_BUCKET;
          const location = `s3://${bucket}/${key}/`

          fs.writeFileSync('/tmp/location', location);
          fs.writeFileSync('/tmp/bucket', bucket);
          fs.writeFileSync('/tmp/key', key);
          console.log(JSON.stringify({
              time: Date.now(),
              level: 20,
              pid: 1,
              msg: 'Workflow:Location',
              location,
              bucket,
              key,
            }),)
