# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: create-thumbnails
  labels:
    linz.govt.nz/category: util
    linz.govt.nz/data-type: raster
    linz.govt.nz/data-sub-type: maps
spec:
  parallelism: 50
  nodeSelector:
    karpenter.sh/capacity-type: spot
  entrypoint: main
  arguments:
    parameters:
      - name: version_argo_tasks
        value: v4
      - name: version_topo_imagery
        value: v4
      - name: source
        value: 's3://linz-topographic-upload/maps/topo50/'
      - name: include
        value: '.*.tiff?$'
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  templates:
    - name: main
      dag:
        tasks:
          - name: aws-list
            template: aws-list

          - name: get-location
            templateRef:
              name: tpl-get-location
              template: main

          - name: thumbnails
            template: thumbnails
            arguments:
              parameters:
                - name: target
                  value: '{{tasks.get-location.outputs.parameters.location}}thumbnails/'
              artifacts:
                - name: files
                  from: '{{ tasks.aws-list.outputs.artifacts.files }}'
            depends: 'aws-list && get-location'
      # END TEMPLATE `main`

    - name: aws-list
      container:
        image: 019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{workflow.parameters.version_argo_tasks}}
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - list
          - --verbose
          - --include
          - '{{workflow.parameters.include}}'
          - --group
          - '2000'
          - --output
          - /tmp/file_list.json
          - '{{workflow.parameters.source}}'

      outputs:
        artifacts:
          - name: files
            path: /tmp/file_list.json

    - name: thumbnails
      nodeSelector:
        karpenter.sh/capacity-type: spot
      inputs:
        parameters:
          - name: target
        artifacts:
          - name: files
            path: /tmp/file_list.json
      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/topo-imagery:{{=sprig.trim(workflow.parameters.version_topo_imagery)}}'
        resources:
          requests:
            memory: 7.8Gi
            cpu: 15000m
            ephemeral-storage: 3Gi
        volumeMounts:
          - name: ephemeral
            mountPath: /tmp
        args:
          - python
          - /app/scripts/thumbnails.py
          - --from-file
          - /tmp/file_list.json
          - --target
          - '{{inputs.parameters.target}}'

  volumes:
    - name: ephemeral
      emptyDir: {}
