# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for copying a manifest of files between two locations
  # See https://github.com/linz/argo-tasks#copy
  name: tpl-copy
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: file
            description: Path to the manifest file detailing source and target

          - name: version_argo_tasks
            description: version of argo-tasks to use
            default: 'v5'

          - name: copy_option
            description: --no-clobber Skip overwriting existing files. --force Overwrite all files. --force-no-clobber Overwrite only changed files, skip unchanged files.
            default: '--no-clobber'
            enum:
              - '--no-clobber'
              - '--force'
              - '--force-no-clobber'

          - name: compress
            description: Compress the files in their target location
            default: 'false'
            enum:
              - 'true'
              - 'false'

          - name: decompress
            description: Decompress the files in their target location
            default: 'false'
            enum:
              - 'true'
              - 'false'

          - name: delete_source
            description: Delete the source files after copying
            default: 'false'
            enum:
              - 'true'
              - 'false'

          - name: aws_role_config_path
            description: s3 URL or comma-separated list of s3 URLs allowing the workflow to write to a target(s)
            default: 's3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config-write.elevation.json,s3://linz-bucket-config/config-write.topographic.json'

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        resources:
          requests:
            memory: 7.8Gi
            cpu: 2000m
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: '{{inputs.parameters.aws_role_config_path}},s3://linz-bucket-config/config.json'
        args:
          - 'copy'
          - '{{inputs.parameters.copy_option}}'
          - '{{inputs.parameters.file}}'
          - '--compress={{inputs.parameters.compress}}'
          - '--decompress={{inputs.parameters.decompress}}'
          - '--delete-source={{inputs.parameters.delete_source}}'
