# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for deleting files that are `source` in a manifest
  # See https://github.com/linz/argo-tasks#delete
  name: tpl-delete
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: file
            description: Path to the manifest file detailing source to delete

          - name: version_argo_tasks
            description: version of argo-tasks to use
            default: 'v4'

          - name: dry_run
            description: 'If true, the command will not delete any files.'
            default: false'
            enum:
              - 'true'
              - 'false'

          - name: aws_role_config_path
            description: s3 URL or comma-separated list of s3 URLs allowing the workflow to write to a target(s)
            default: 's3://linz-bucket-config/config-write.imagery.json,s3://linz-bucket-config/config-write.elevation.json,s3://linz-bucket-config/config-write.topographic.json'

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(workflow.parameters.version_argo_tasks)}}'
        resources:
          requests:
            memory: 7.8Gi # TODO: to review
            cpu: 2000m # TODO: to review
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: '{{inputs.parameters.aws_role_config_path}},s3://linz-bucket-config/config.json'
        args:
          - 'delete'
          - '--dry-run={{inputs.parameters.dry_run}}'
          - '{{inputs.parameters.file}}'
