# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template from linz/argo-tasks
  # see https://github.com/linz/argo-tasks#group
  name: tpl-at-group
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        artifacts:
          #
          # JSON array of things to group
          #
          # @example
          # ```json
          # ["a.json", "b.json", "c.json"]
          # ```
          - name: input
            path: /tmp/group/input.json

        parameters:
          - name: size
            description: Group into this number of records per group

          - name: version
            description: argo-task Container version to use
            default: v4

      outputs:
        parameters:
          #
          # JSON array of all the group ids, which correspond to a output artifact file
          #
          # @example
          # ```json
          # ["000", "001", "002", "003"]
          # ```
          #
          # Workflows should use the "000" string to access the data from the output artifact folder
          - name: output
            valueFrom:
              path: /tmp/group/output.json

        artifacts:
          # Grouped output of the input as one file per output groupId
          #
          # - /output/000.json
          # - /output/001.json
          # - ...
          #
          - name: output
            path: /tmp/group/output/

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{= inputs.parameters.version }}'
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - group
          - --verbose
          - '--size={{= inputs.parameters.size }}'
          - '--from-file={{= inputs.artifacts.input.path }}'
