# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template from linz/argo-tasks
  # see https://github.com/linz/argo-tasks#tileindex-validate
  name: tpl-at-identify-updated-items
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: targetCollection
            description: collection.json file of the target collection
            default: ''
          - name: sourceCollections
            description: List of source collection.json files (semicolon delimited)
            default: ''
          - name: version
            description: 'Specify a version of the argo-tasks image to use, e.g. "v1.0" or "latest"'
            default: 'v4'

      outputs:
        artifacts:
          # List of tiff files that need to be processed
          - name: files
            path: /tmp/identify-updated-items/file-list.json
            optional: true
            archive:
              none: {}

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=inputs.parameters.version}}'
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - 'identify-updated-items'
          - '--verbose'
          - '{{= inputs.parameters.targetCollection == "" ? "" : "--target-collection=" + inputs.parameters.targetCollection }}'
          - '{{= inputs.parameters.sourceCollections }}'
