# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.13/api/jsonschema/schema.json
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template for Formatting and Pushing STAC Collections to Github
  # See https://github.com/linz/argo-tasks#stac-github-import
  name: tpl-push-to-github
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      retryStrategy:
        limit: '2'
      inputs:
        parameters:
          - name: source
            description: location where the source collection.json file is

          - name: target
            description: location where the destination collection.json file will be

          - name: version_argo_tasks
            description: version of argo-tasks to use
            default: 'v3'

          - name: repository
            description: Repository Name
            default: ''
            enum:
              - 'elevation'
              - 'imagery'

          - name: ticket
            description: Ticket ID e.g. 'AIP-55'
            default: ''

          - name: copy_option
            description: --no-clobber Skip overwriting existing files. --force Overwrite all files. --force-no-clobber Overwrite only changed files, skip unchanged files.
            default: '--no-clobber'

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(inputs.parameters.version_argo_tasks)}}'
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
          - name: GITHUB_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: github-linz-li-bot-pat
                key: pat
        command: [node, /app/index.js]
        args:
          [
            'stac',
            'github-import',
            '--source',
            '{{=sprig.trim(inputs.parameters.source)}}',
            '--target',
            '{{inputs.parameters.target}}',
            '--repo-name',
            'linz/{{=sprig.regexFind(inputs.parameters.repository, inputs.parameters.target)}}',
            '--ticket',
            '{{inputs.parameters.ticket}}',
            '--copy-option',
            '{{inputs.parameters.copy_option}}',
          ]
