# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template from linz/argo-tasks
  # see https://github.com/linz/argo-tasks#stac-setup
  name: tpl-at-stac-setup
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: start_datetime
            description: '(Optional) Dataset capture start date in numeric format YYYY-MM-DD'
            default: ''
          - name: end_datetime
            description: '(Optional) Dataset capture end date in numeric format YYYY-MM-DD'
            default: ''
          - name: gsd
            description: 'Dataset GSD in metres'
          - name: region
            description: 'Region of the dataset'
          - name: geographic_description
            description: '(Optional) Additional dataset description'
            default: ''
          - name: geospatial_category
            description: 'Geospatial category of the dataset'
          - name: survey_id
            description: '(Optional) Survey Number associated with historical datasets, e.g. "SN8844"'
            default: ''
          - name: odr_url
            description: '(Optional) S3 path to existing dataset collection.json'
            default: ''
          - name: version
            description: 'argo-task Container version to use'
            default: 'v5'

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=inputs.parameters.version}}'
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - 'stac'
          - 'setup'
          - '--region={{inputs.parameters.region}}'
          - '--geospatial-category={{inputs.parameters.geospatial_category}}'
          - '--gsd={{inputs.parameters.gsd}}'
          - "{{= sprig.empty(inputs.parameters.start_datetime) ? '' : '--start-year=' + sprig.trunc(4, inputs.parameters.start_datetime) }}"
          - "{{= sprig.empty(inputs.parameters.end_datetime) ? '' : '--end-year=' + sprig.trunc(4, inputs.parameters.end_datetime) }}"
          - "{{= sprig.empty(inputs.parameters.geographic_description) ? '' : '--geographic-description=' + inputs.parameters.geographic_description }}"
          - "{{= sprig.empty(inputs.parameters.survey_id) ? '' : '--survey-id=' + inputs.parameters.survey_id }}"
          - "{{= sprig.empty(inputs.parameters.odr_url) ? '' : '--odr-url=' + inputs.parameters.odr_url }}"

      outputs:
        parameters:
          - name: collection_id
            description: ID for collection and item STAC
            valueFrom:
              path: '/tmp/stac-setup/collection-id'
          - name: linz_slug
            description: linz:slug field for collection STAC
            valueFrom:
              path: '/tmp/stac-setup/linz-slug'
