# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.6.12/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template from linz/argo-tasks
  # see https://github.com/linz/argo-tasks?tab=readme-ov-file#stac-validate
  name: tpl-at-stac-validate
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: uri
            description: STAC file uri to validate
            default: ''

          - name: recursive
            description: Follow and validate STAC links
            default: 'true'

          - name: concurrency
            description: Number of requests to run concurrently
            default: '50'

          - name: checksum_assets
            description: Validate the file:checksum of each asset if it exists
            default: 'false'

          - name: checksum_links
            description: Validate the file:checksum of each link if it exists
            default: 'false'

          - name: version
            description: container version to use
            default: 'v4'

          - name: aws_role_config_path
            description: s3 URL or comma-separated list of s3 URLs allowing the workflow to write to a target(s)
            value: 's3://linz-bucket-config/config.json'

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=sprig.trim(inputs.parameters.version)}}'
        resources:
          requests:
            cpu: 15000m
            memory: 7.8Gi
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: '{{inputs.parameters.aws_role_config_path}}'
        args:
          - 'stac'
          - 'validate'
          - '--concurrency={{inputs.parameters.concurrency}}'
          - '--recursive={{inputs.parameters.recursive}}'
          - '--checksum-assets={{inputs.parameters.checksum_assets}}'
          - '--checksum-links={{inputs.parameters.checksum_links}}'
          - '{{inputs.parameters.uri}}'
