# yaml-language-server: $schema=https://raw.githubusercontent.com/argoproj/argo-workflows/v3.5.5/api/jsonschema/schema.json

apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # Template from linz/argo-tasks
  # see https://github.com/linz/argo-tasks#tileindex-validate
  name: tpl-at-tile-index-validate
spec:
  templateDefaults:
    container:
      imagePullPolicy: Always
      image: ''
  entrypoint: main
  templates:
    - name: main
      inputs:
        parameters:
          - name: scale
            description: Tile Index scale to validate against or target scale for retiling. "auto" determines the appropriate scale based on input TIFFs GSD and preset
            default: 'auto'

          - name: source_epsg
            description: Force source EPSG, "" will attempt to load EPSG from the source tiffs
            default: ''

          - name: source
            description: Location to list
            default: ''

          - name: include
            description: Limit the input list to this regexp
            default: ''

          - name: includeDerived
            description: Sets includeDerived=true/false in file-list.json
            default: 'false'

          - name: validate
            description: Validate that all input tiffs perfectly align to tile grid. "auto" skips validation when retiling
            default: 'auto'

          - name: retile
            description: Output tile configuration for retiling. "auto" enables intelligent re-tiling based on input vs output scales
            default: 'auto'

          - name: preset
            description: Compression type of dataset e.g. webp, lzw, dem_lerc
            default: 'webp'

          - name: version
            description: container version to use
            default: 'v4'

      outputs:
        parameters:
          - name: gsd
            description: 'GSD of the input tiffs'
            valueFrom:
              path: /tmp/tile-index-validate/gsd

        artifacts:
          # List of tiff files that need to be processed
          - name: files
            path: /tmp/tile-index-validate/file-list.json
            optional: true
            archive:
              none: {}

          # GeoJSON containing all the bounding box of all input tiffs
          - name: input
            path: /tmp/tile-index-validate/input.geojson
            optional: true
            archive:
              none: {}

          # GeoJSON containing the bounding boxes of all the output tiffs
          - name: output
            path: /tmp/tile-index-validate/output.geojson
            optional: true
            archive:
              none: {}

      container:
        image: '019359803926.dkr.ecr.ap-southeast-2.amazonaws.com/argo-tasks:{{=inputs.parameters.version}}'
        env:
          - name: AWS_ROLE_CONFIG_PATH
            value: s3://linz-bucket-config/config.json
        args:
          - 'tileindex-validate'
          - '--verbose'
          - '--scale={{= inputs.parameters.scale }}'
          - '--validate={{= inputs.parameters.validate }}'
          - '--retile={{= inputs.parameters.retile }}'
          - '--preset={{= inputs.parameters.preset }}'
          - "{{= sprig.empty(inputs.parameters.source_epsg) ? '' : '--source-epsg=' + inputs.parameters.source_epsg }}"
          - "{{= sprig.empty(inputs.parameters.include) ? '' : '--include=' + inputs.parameters.include }}"
          - '--includeDerived={{= inputs.parameters.includeDerived }}'
          - '{{= sprig.trim(inputs.parameters.source) }}'
        resources:
          requests:
            memory: 3.9Gi
