name: Deploy workflows in PR namespace
on:
  pull_request:
    types: labeled
jobs:
  deploy-workflows:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'workflows'
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      AWS_CI_ROLE: ${{ secrets.AWS_CI_ROLE }}
      CLUSTER_NAME: Workflows
      NAMESPACE: pr-${{ github.event.number }}
    steps:
      - uses: linz/action-typescript@9bf69b0f313b3525d3ba3116f26b1aff7eb7a6c0 # v3.1.0
        with:
          node-version: 20.x
      # Configure access to AWS / EKS
      - name: Setup kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v3
        with:
          version: 'latest'
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_CI_ROLE }}
      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ap-southeast-2
      - name: Check EKS connection
        run: |
          kubectl get nodes
      - name: Create namespace
        run: |
          # Create the namespace for the PR
          kubectl create namespace "${{ env.NAMESPACE }}"

      - name: Create ServiceAccount
        run: |
          NS="${{ env.NAMESPACE }}"

          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: workflow-runner-sa
            namespace: ${NS}
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: argo-workflows-workflow
            namespace: ${NS}
          rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "watch", "list", "create", "delete", "patch"]
            - apiGroups: [""]
              resources: ["pods/log"]
              verbs: ["get", "watch"]
            - apiGroups: [""]
              resources: ["pods/exec"]
              verbs: ["create"]
            - apiGroups: [""]
              resources: ["configmaps"]
              verbs: ["get", "watch", "list"]
            - apiGroups: ["argoproj.io"]
              resources: ["workflows"]
              verbs: ["get", "watch", "list", "create", "delete", "update"]
            - apiGroups: ["argoproj.io"]
              resources: ["workflowtaskresults"]
              verbs: ["create", "patch"]
            - apiGroups: ["argoproj.io"]
              resources: ["workflowtasksets", "workflowartifactgctasks"]
              verbs: ["list", "watch"]
            - apiGroups: ["argoproj.io"]
              resources: ["workflowtasksets/status", "workflowartifactgctasks/status"]
              verbs: ["patch"]
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: argo-workflows-workflow
            namespace: ${NS}
          roleRef:
            kind: Role
            name: argo-workflows-workflow
            apiGroup: rbac.authorization.k8s.io
          subjects:
            - kind: ServiceAccount
              name: workflow-runner-sa
              namespace: ${NS}
          EOF

      - name: Deploy Semaphore config
        run: |
          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: semaphores
            namespace: ${{ env.NAMESPACE }}
          data:
            basemaps_import: "10"
            bulk: "4"
            bulkcopy: "8"
            standardising: "2"
          immutable: false
          EOF

      - name: Deploy workflows
        run: |
          NS="${{ env.NAMESPACE }}"
          # Create copy of Workflows files to change their namespaces
          mkdir test
          cp -r workflows/ test/workflows/ 

          # Deploy templates in the test namespace
          # Note: the templates have no default namespace so no need to modify them
          # Find all templates that have kind "WorkflowTemplate"
          TEMPLATES=$(grep '^kind: WorkflowTemplate$' -R templates/ -H | cut -d ':' -f1)
          # For each template attempt to deploy it using kubectl
          for tpl in $TEMPLATES; do
              kubectl apply -f "$tpl" --namespace "$NS"
          done

          # Find all workflows that have kind "WorkflowTemplate"
          WORKFLOWS=$(grep -R -H '^kind: WorkflowTemplate$' test/workflows/ | cut -d ':' -f1)
          # For each workflow attempt to deploy it using kubectl
          for wf in $WORKFLOWS; do
              # Change namespace in files
              sed -i "/^\([[:space:]]*namespace: \).*/s//\1$NS/" "$wf"
              kubectl apply -f "$wf" --namespace "$NS"
          done
