name: Delete PR namespace

on:
  pull_request:
    types: [closed, unlabeled]

jobs:
  cleanup:
    if: |
      github.event.pull_request.merged == true || (
        github.event.label.name == 'workflows' && github.event.action == 'unlabeled'
      )
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    env:
      CLUSTER_NAME: Workflows

    steps:
      - uses: linz/action-typescript@9bf69b0f313b3525d3ba3116f26b1aff7eb7a6c0 # v3.1.0
        with:
          node-version: 20.x
        # Configure access to AWS / EKS
      - name: Setup kubectl
        uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v3
        with:
          version: 'latest'
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_CI_ROLE }}
      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ap-southeast-2
      - name: Check EKS connection
        run: |
          kubectl get nodes
      - name: Delete Test namespace
        run: |
          # Delete the test namespace
          TEST_NAMESPACE=pr-${{ github.event.pull_request.number }}
          stderr_tmp="$(mktemp --directory)/stderr"
          if ! kubectl delete namespaces "$TEST_NAMESPACE" 2> >(tee "$stderr_tmp" >&2)
          then 
              grep -q 'Error from server (NotFound): namespaces ".*" not found' "$stderr_tmp"
          fi
